### ISSUE TITLE
scenedetect reading 0x0 video resoultion and 0 fps, then freeze

### ISSUE THREAD

**Issue by chakree30584** [Breakthrough/PySceneDetect#10]
this is what I got from command
$ ./scenedetect.py --input ../testvideo.mp4 --output ../test.csv --detector content --threshold 30 -fs 2 -df 2 -l
[PySceneDetect] Detecting scenes (content mode)...
[PySceneDetect] Parsing video ../testvideo.mp4...
[PySceneDetect] Video Resolution / Framerate: 0 x 0 / 0.000 FPS
[PySceneDetect] Subsampling Enabled (2x, Resolution = 0 x 0)
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).

running on CentOs 7.0 , Python 2.7.5
please help
Thanks

**Comment by Breakthrough** [comment]
Hi @chakree30584 it looks like the OpenCV FFMPEG module isn't loading the video file properly.  There's two possibilities here, the first is a corrupted video file, the second is using an outdated version of OpenCV or FFMPEG.

Are you able to run PySceneDetect on other videos fine, or do you get the same output each time (with resolution/framerate returned as `0`)?  What version of OpenCV are you running on your system?

If you suspect the video is the problem, you can try putting it into an `mkv` container by running `mkvmerge` on it.  If the video has no problems, try using a different version of OpenCV, and if possible, compile OpenCV manually from source, ensuring you have the latest version of `ffmpeg`.

**Comment by chakree30584** [comment]
OpenCV version from base repo is 2.4.5

i couldn't find a way to compile OpenCV on CentOS7.0, stuck in lots of dependency error
so I move to ubuntu 14.04.3 by following your guide in documentation
and it's working now

Thanks for your help

**Comment by Breakthrough** [comment]
Glad you got it worked out @chakree30584.  I didn't realize the repo version was so old...

Thanks for bringing this to my attention, I'll make sure this behaviour is detected in the future, and that PySceneDetect exits properly, displaying an error message and a notification to update the installed version of OpenCV.
