### ISSUE TITLE
Ask for help (by Newbie)

### ISSUE THREAD

**Issue by ThisMoment1** [Breakthrough/PySceneDetect#113]
Hey anybody，I got some mistakes by the following command line:

>>scenedetect --input video.avi  --stats video_minlen25.stats.csv detect-content --threshold 30 list-scenes   --min-scene-len 25

where the information as follows:

>>[PySceneDetect] Loaded 1 video, framerate: 25.00 FPS, resolution: 640 x 480
>>[PySceneDetect] Downscale factor set to 3, effective resolution: 213 x 160
>>[PySceneDetect] No scene detectors specified (detect-content, detect-threshold, etc...),
  or failed to process all command line arguments.
>>Usage: scenedetect list-scenes [OPTIONS]

>>Error: no such option: --min-scene-len

If you can answer me, I will be very grateful.  And  @Breakthrough , Thanks for your work!

**Comment by Breakthrough** [comment]
Hi @ThisMoment1;

There is no --min-scene-len option for the detect-content or list-scenes command, that's why you're facing this issue.  --min-scene-len is only applied to `detect-threshold`.  If you use this command, it will work:

    scenedetect --input video.avi --stats video_min.stats.csv detect-content --threshold 30 list-scenes

If you would like, you can file a feature request for adding a minimum scene length flag to the `detect-content` command. 

Thanks.

**Comment by ThisMoment1** [comment]
@Breakthrough, Thank you very much for your reply, which is very helpful to me.In addition, I think it may be possible to add the function of `--min-scene-len` to `detect-content`, so as to increase the operability.

**Comment by ThisMoment1** [comment]
@Breakthrough, thank you very much for your reply, which is very helpful to me. In addition, I will try to submit a feature request -- to add the` --min-scene-len`  flag to `detect-content` command. Thanks for your work and advice.

**Comment by Breakthrough** [comment]
Hi @ThisMoment1;

Sorry, I forgot that there IS actually a `--min-scene-len` flag for `detect-content`.  My apologies.  What you want for your original command is:

    scenedetect --input video.avi --stats video_minlen25.stats.csv detect-content --threshold 30 --min-scene-len 25 list-scenes

Let me know if this helps.  Thanks!

**Comment by ThisMoment1** [comment]
Hi, @Breakthrough ;

Yes, it works. Thanks for your paitent advice.
