### ISSUE TITLE
Feature request: Add --min-scene-len flag to detect-content command

### ISSUE THREAD

**Issue by ThisMoment1** [Breakthrough/PySceneDetect#114]
Hi @Breakthrough ,

Thank you very much for your awesome software!

Now I'm having  some problems of getting what I want. I have a requirement that the detected scenes should be no less than _n_ frames, but there seems to be no such flag for `detect-content`. 

Would you consider adding this flag to the `detect-content` command?

Many thanks!

**Comment by Breakthrough** [comment]
Closing as invalid due to feature already existing.

(This was my mistake, I indicated that it was not exposed to the CLI yet, but this was not the case, my apologies!)
