### ISSUE TITLE
Complete documentation for Video Splitter API

### ISSUE THREAD

**Issue by dynamite-ready** [Breakthrough/PySceneDetect#116]
**Bug/Issue Description:**
Calls to `scenedetect.video_splitter.split_video_mkvmerge` end with a `ERROR:root:Error splitting video (mkvmerge returned 2).`

**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using, for example:

Example Python API call:
`scenedetect.video_splitter.split_video_mkvmerge(str(video_path), scene_list, "test", "tests", suppress_output=False)`

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.

**Expected Behavior:**
`mkvmerge v37.0.0 ('Leave It') 64-bit
'spring.mp4': Using the demultiplexer for the format 'QuickTime/MP4'.
'spring.mp4' track 0: Using the output module for the format 'AVC/H.264'.
'spring.mp4' track 1: Using the output module for the format 'AAC' # etc...`

**Computing Environment:**
 - OS: Windows 10
 - Python Version: 3.7
 - OpenCV Version: Unknown

**Additional Information:**
Fixed by a small change to the method in question.
A commit on my fork with a candidate fix can be found here - https://github.com/dynamite-ready/PySceneDetect/commit/3006d871fbeb53ed01866a01edbad87e055fb1e4

**Comment by Breakthrough** [comment]
Hello @dynamite-ready;

The `input_video_paths` argument is supposed to be a list, not a string.  If you refactor the call you have above:

    scenedetect.video_splitter.split_video_mkvmerge(str(video_path), scene_list, "test", "tests", suppress_output=False)

To the following:

    scenedetect.video_splitter.split_video_mkvmerge([str(video_path)], scene_list, "test", "tests", suppress_output=False)

That should resolve the error that you're seeing.  The intention of the `split_video_` functions is to allow multiple videos as input files, which will be concatenated together in the output.

**Comment by Breakthrough** [comment]
Ping: Revisit this next week for v0.6.  Top priorities right now are resolving ffmpeg split issues and camera flash issue resolution, but I don't want to lose track of quality-of-life items like this one.

**Comment by Breakthrough** [comment]
Ugh, for some reason, the documentation that now gets generated is completely blank for the video splitter.  I've submitted a support request for ReadTheDocs, but in the meantime I'll try to come up with a workaround.

Broken:
https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api/video_splitter.html
https://pyscenedetect.readthedocs.io/projects/Manual/en/v0.5.2/api/video_splitter.html

Working:
https://pyscenedetect.readthedocs.io/projects/Manual/en/v0.5.1/api/video_splitter.html
https://pyscenedetect.readthedocs.io/projects/Manual/en/v0.6.x/api/video_splitter.html

Either way, I'll get this closed out this week as well, but just wanted to keep you posted.
