### ISSUE TITLE
No split of Video

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#119]
**Bug/Issue Description:**
Video works well but One File created without no split

**Required Information:**
https://www.youtube.com/watch?v=piNM-RnzNWs
`scenedetect -i "D:\Rlife.mp4" -o "D:\ex" detect-threshold -t 12 -p 95 split-video --copy`

**Expected Behavior:**
Need some split of this video!

**Computing Environment:**
 - OS: Win 10 Pro
 - Python Version: 64bit 3.7.4
 - OpenCV Version: Latest

**Media [Videos/Images/Screenshots]:**
https://www.youtube.com/watch?v=piNM-RnzNWs

**Comment by Breakthrough** [comment]
Hey @raj6996;

Where are you expecting the threshold split in this video, at the end?   (approx. what timecode??)

I would try with `-t 20 -p 80` (and keep raising `-t`) and see if you can get it to detect the fades.  Thanks!

**Comment by Breakthrough** [comment]
Closing issue as no response has been received; feel free to re-open it when you can provide the necessary information.  Thank you!
