### ISSUE TITLE
Change output video names

### ISSUE THREAD

**Issue by arianaa30** [Breakthrough/PySceneDetect#120]
Is there any ways to specify/remove the output video names? Right now we get a format like `[input]-Scene-001.mp4`, but I would like to remove the `Scene` part, or maybe only `001.mp4`. Any ways we can specify that?

**Comment by Breakthrough** [comment]
Hi @arianaa30;

With the `split-video` command, you can specify the output filename with the `-f`/`--filename` option, where you can use `$VIDEO_NAME` and `$SCENE_NUMBER`.

The default format for `-f` is `$VIDEO_NAME- Scene-$SCENE_NUMBER`.  To achieve what you want, you can specify:

    split-video -f "$SCENE_NUMBER"

Or:

    split-video -f "$VIDEO_NAME-$SCENE_NUMBER"

See [the manual](https://pyscenedetect-manual.readthedocs.io/en/latest/cli/commands.html#split-video) for details.  Thank you!
