### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by mrobe** [Breakthrough/PySceneDetect#121]
I get this error when running `scenedetect --version`

I see this has been reported as fixed before (however, on Windows, not macOS, it seems). I added a comment to the end of that issue, but I'm not sure how to reopen it.

**Computing Environment:**
 - OS: macOS 10.13.6
 - Python Version: 3.6.5
 - OpenCV Version: 4.1.1(?)

```
Python 3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.1'
>>> exit()
```

The full error:
```
Traceback (most recent call last):
  File "/usr/local/bin/scenedetect", line 11, in <module>
    load_entry_point('scenedetect==0.5.1.1', 'console_scripts', 'scenedetect')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/scenedetect-0.5.1.1-py3.7.egg/scenedetect/__init__.py", line 52, in <module>
  File "/usr/local/lib/python3.7/site-packages/scenedetect-0.5.1.1-py3.7.egg/scenedetect/scene_manager.py", line 55, in <module>
ModuleNotFoundError: No module named 'cv2'
```

**Comment by Breakthrough** [comment]
Hi @mrobe;

It seems like you have both Python 3.6 *and* 3.7 installed.  Indeed it seems like you have OpenCV installed for your Python 3.6 interpreter, but for some reason you're invoking PySceneDetect with the Python 3.7 interpreter.

Can you try running PySceneDetect in your Python 3.6 environment instead, or double-checking that, when you run Python 3.7, you can successfully `import cv2`?

Thanks for your submission.

**Comment by mrobe** [comment]
I tried to reinstall python to use version 3.6.5. Here are the results:

```
$ which python3
/usr/local/bin/python3
$ python3 --version
Python 3.6.5
```
However, I am still getting the "module not found: cv2" error.

I feel like this should not be so complicated. When I google for help to do this, there are a zillion pages about trying to fiddle around with python versions -- and a half-zillion different answers. It seems like dozens of people are stuck python's own version of DLL hell.

Question: has scenedetect been ported to any other languages that have a better runtime environment?

**Comment by Breakthrough** [comment]
Perhaps re-install PySceneDetect under the Python 3.6.5 environment via pip
(after uninstalling it from 3.7), or consider using a virtualenv.

My apologies, I'm not too familiar with multiple versions of the same major
Python environment installed (I normally use virtualenvs for this
purpose).  I am considering rewriting the core of PySceneDetect in C++ for
better performance, but as-is there are no plans to move PySceneDetect
itself away from Python (it will simply invoke the new SceneStats
executable).

Hope this helps, best wishes.

**Comment by mrobe** [comment]
Thanks for the tips. I tried reinstalling with pip, as you suggested, and that has allowed me to get past the previous error.

**Comment by mrobe** [comment]
It works! I have some usage questions, but I'll ask them elsewhere. Closing this issue.
