### ISSUE TITLE
UnboundLocalError in detect_scenes when frame_skip is larger than 0.

### ISSUE THREAD

**Issue by twostarxx** [Breakthrough/PySceneDetect#126]
**Bug/Issue Description:**

"UnboundLocalError: local variable 'read_frame' referenced before assignment" when running `scene_manager.detect_scenes(frame_source=video_manager, frame_skip=1)`

**Required Information:**

We hit this error when `frame_skip` is larger than 0.

**Expected Behavior:**

It works when we assign frame_skip.

**Computing Environment:**
 - OS: [e.g. Windows, Linux (Distro: Ubuntu, Mint, Fedora, etc...), OSX]
 - Python Version: [e.g. 3.6 or 3.6.6]
 - OpenCV Version: [e.g. 3.4.1]

**Additional Information:**

**Comment by Breakthrough** [comment]
Thank you for your issue report and pull request!

This will be included in the next release of PySceneDetect, thank you so much.
