### ISSUE TITLE
Is there any implementation of cutting the moving scene?

### ISSUE THREAD

**Issue by sontallive** [Breakthrough/PySceneDetect#132]
I want to use this tool in the home surveillance video. Because I want to compress the video so I need to cut only the moving scene and throw the static scene. I thought I need to use the Threshold Detector but it's based on fading in and fading out. Is there any solution to achieve this?

**Comment by sontallive** [comment]
ok, I found that I need to use the content detector

**Comment by Breakthrough** [comment]
Hi @sontallive;

You might want to use [DVR-Scan](https://github.com/Breakthrough/DVR-Scan) for that instead.  It will eventually be merged with PySceneDetect as a motion detector.

Thanks!
