### ISSUE TITLE
Does this tool provide the same function as DVR-Scan?

### ISSUE THREAD

**Issue by sontallive** [Breakthrough/PySceneDetect#133]
Does this tool provide the same function as DVR-Scan?

**Comment by sontallive** [comment]
Does this tool provide the same function as DVR-Scan?

**Comment by Breakthrough** [comment]
Closing as duplicate of #43 (most recent discussion [here](https://github.com/Breakthrough/PySceneDetect/issues/43#issuecomment-527225973)).  TL,DR:  No, currently PySceneDetect does not provide the same functionality, although the plan of record is to eventually combine it's functionality and depreciate DVR-Scan.
