### ISSUE TITLE
Rotate scene output images according to video metadata

### ISSUE THREAD

**Issue by markbaumgarten** [Breakthrough/PySceneDetect#134]
**Description of Problem & Solution**
Videos recorded using cell phones plays fine in software like VLC(because vlc reads the video metadata).

Using opencv2 to output thumbs from files that are recorded 'sideways' outputs thumbs that are rotated - because opencv ignores the metadata. By using ffprobe to detect rotations this problem can be mitigated.

I am using pyscenedetect in an effort to do video deduplication/recognition - and it is essential that I am able to detect/fix rotated videos.

**Media Examples:**
Sorry - will try to provide examples later

**Proposed Implementation:**
Please have a look here:

https://github.com/markbaumgarten/PySceneDetect/commit/6a3a8a36eb67bddbdaef1b80eac3482739676213

...still a noob with regards to creating a proper pull...or merge...? request. Apologies for any inconvenience. Hints for me to do this the right way are very welcome.

**Alternative Solutions:**
None I know of

**Comment by Breakthrough** [comment]
Hi @markbaumgarten;

This is definitely something I would like to add to PySceneDetect, so thank you for providing a reference implementation.  The only thing I would add to the code you wrote is an additional check to detect if `ffprobe` is available.

I am also wondering, do you know of any other tools (or preferably, native Python libraries) which can also determine this information?

Thank you!

**Comment by markbaumgarten** [comment]
I have added a check for ffprobe presence now. Not sure how to inform the
user he should install ffprobe.

I personally wrap all of my software in docker containers so stuff like
this is not much of an issue in my end.

There are ffprobe pip packages, but when trying to use them I have had some
issues I did not manage to fix.

I believe that my code is only valid for python 3.3+ - hoping this is not
an issue.

Best regards and many thanks for creating scenedetect.

Mark

**Comment by Breakthrough** [comment]
Will revisit this for v0.6.1.  This may need to only be conditionally enabled if ffprobe is available, and have a corresponding FAQ entry detailing the fix (which would be to install ffprobe).  There should also be an option to disable the feature if it's auto-enabled, both via the CLI and the config file.

Your original function appeared as:

```python
def get_rotation(file_path):
    # type: (str) -> str
    """ Get Rotation: Returns the number of degrees a video has been rotated.
    Uses subprocess to call external program ffprobe on the video.
    """
    cmd = '''ffprobe -loglevel error -select_streams v:0 -show_entries stream_tags=rotate \
             -of default=nw=1:nk=1 -i "%s"''' % file_path
    rotation = subprocess.getoutput(cmd)
    return rotation or None
```

This should probably go somewhere in the `scenedetect.platform` module, and then only be done in the actual `save_images` command/function.  This avoids a potentially expensive rotation during the detection phase (video orientation shouldn't have an impact on detector performance).

**Comment by Breakthrough** [comment]
@markbaumgarten what version of OpenCV were you using when you ran into this?  Can you try again with the latest version?  It seems to be working all of the sudden without any changes on my end, at least when using OpenCV.

**Comment by Breakthrough** [comment]
Will mark this as complete for using the OpenCV backend (default) as this should work now with a new version of OpenCV.

If required on other backends please file a feature request.  Thanks.
