### ISSUE TITLE
Video Splitting using Custom `FrameTimecode`s, Doc Improvements

### ISSUE THREAD

**Issue by rsomani95** [Breakthrough/PySceneDetect#137]
I'm trying to use `split_video_ffmpeg` from `scenedetect.video_splitter` using custom `FrameTimecode`s.

<br>

**Context: I've got a list of frames that I'd like to split the video on using ffmpeg.**

### Step 1: Setting up a list of custom `FrameTimecode`

```python
peaks = [21.0, 58.0, 86.0]
fps = 23.976024259799487
scene_list = [FrameTimecode(int(x), fps) for x in peaks]
```

### Step 2: Using `split_video_ffmpeg`
From the source file:
```python
def split_video_ffmpeg(input_video_paths, scene_list, output_file_template, video_name,
                       arg_override='-c:v libx264 -preset fast -crf 21 -c:a copy',
                       hide_progress=False, suppress_output=False):
    # type: (List[str], List[Tuple[FrameTimecode, FrameTimecode]], Optional[str],
    #        Optional[str], Optional[bool]) -> None
```
This tells me (wrongly) that `input_video_paths` and `scene_list` (as set up above I presume) is all that I would need to use this function. On trying...
```python
split_video_ffmpeg(['some_video.mp4'], scene_list)
```
... I got this error:
```python
TypeError: split_video_ffmpeg() missing 2 required positional arguments: 'output_file_template' and 'video_name'
```
---
It was a bit cumbersome to understand what was happening through the CLI, so I tried some arguments that seemed intuitive:

```python
split_video_ffmpeg(['some_video.mp4'], frame_timecodes, output_file_template='tmp/', video_name='new_vid.mp4')
```
facing this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-113-250d58eeb1fa> in <module>
----> 1 split_video_ffmpeg([video_file], frame_timecodes, output_file_template='zz/', video_name='new.mp4')

~/anaconda3/lib/python3.7/site-packages/scenedetect/video_splitter.py in split_video_ffmpeg(input_video_paths, scene_list, output_file_template, video_name, arg_override, hide_progress, suppress_output)
    211     try:
    212         progress_bar = None
--> 213         total_frames = scene_list[-1][1].get_frames() - scene_list[0][0].get_frames()
    214         if tqdm and not hide_progress:
    215             progress_bar = tqdm(total=total_frames, unit='frame', miniters=1)

TypeError: 'FrameTimecode' object is not subscriptable
```

Thank you in advance for your time!

**Comment by Breakthrough** [comment]
Hello @rsomani95;

The scene_list should be a list of tuple pairs of FrameTimecodes of start frame and end frame, e.g.

    scene_list = [ (Scene1_Start_FrameTimecode, Scene1_End_FrameTimecode), (Scene2_Start, Scene2_End), ... ]

So I think what you want to do here is:

    peaks = [(0, 21.0), (21.0, 58.0), (58.0, 86.0)]
    fps = 23.976024259799487
    scene_list = [(FrameTimecode(int(x), fps), FrameTimecode(int(y), fps)) for (x, y) in peaks]

Lastly, it's known that the documentation needs updating for the video splitting functions; this  is tracked in #116.

Thanks for your submission, let me know if this handles it.

**Comment by rsomani95** [comment]
Thanks @Breakthrough! That handled it just fine.
I'd just like to point out for someone that visits this issue in the future, that the function call requires the `output_file_template` argument to be a filename (w/ extension) which is what the split video gets saved as -- `'result.mp4'` for example. I'm not sure what the `video_name` argument does. 

---

> It would be possible to refactor the code to allow calling with a single cutting list, but I would rather that be eventually made into a separate API call if required (it should also not be difficult to modify the existing solution to support it).

I think it could be possible to do it within the same API call if you check the type of the input. 
Anyways, here's what I used:
```python
peaks = [22, 34, 54, 80,  99] #... as long as you want
scene_list = []
for i in range(len(peaks)):
    if i == 0: scene_list.append((FrameTimecode(0,fps),               FrameTimecode(int(peaks[i]),fps)))
    else:      scene_list.append((FrameTimecode(int(peaks[i-1]),fps), FrameTimecode(int(peaks[i]),fps)))
```
Do you think the above chunk is something that could be modded to be part of the library? If yes, I'd be glad to make a PR. 

Thanks for your help :)
