### ISSUE TITLE
Image filename in HTML needs to be URI escaped

### ISSUE THREAD

**Issue by allenday** [Breakthrough/PySceneDetect#139]
Image filenames can contain special characters (such as `?`). These need to be URI escaped to correctly render the image in the HTML.

**Comment by allenday** [comment]
https://github.com/Breakthrough/PySceneDetect/blob/ed69e21ffa5881ef63652644d864248e5872cb14/scenedetect/thirdparty/simpletable.py#L110

**Comment by Breakthrough** [comment]
Closed by #148 (thanks @wjs018!).
