### ISSUE TITLE
Error in simple example, PySceneDetect Python Interface 

### ISSUE THREAD

**Issue by SoumitraAgarwal** [Breakthrough/PySceneDetect#14]
In the documentation for PySceneDetect [here](https://pyscenedetect.readthedocs.io/en/latest/examples/usage-python/) , the sample program returns the error ` NameError: name 'video_fps' is not defined` . I believe that the correction would be changing it to `video_framerate`. Is there a better place to raise such an issue? :fearful:

**Comment by SoumitraAgarwal** [comment]
Created a pull request with correction #15

**Comment by Breakthrough** [comment]
Hi @SoumitraAgarwal - indeed you are correct!

I've accepted your pull request (0c359d9fae48a948bba11a7b9f42ca597956c7b0), thank you for bringing this to my attention.  Best regards!
