### ISSUE TITLE
Include link in HTML table

### ISSUE THREAD

**Issue by allenday** [Breakthrough/PySceneDetect#140]
- Link to video in an additional column.
- Link each `<img/>` element to open the full image.
- Do both of these `<a/>` elements wth `target=blank`

**Comment by Breakthrough** [comment]
It seems like @wjs018 addressed both of your second points (many thanks!).  As for the link to a video, there should be a command-line flag to turn on/off that behaviour.  Do you still require this modification?  Thanks!

**Comment by Breakthrough** [comment]
Closing until feedback is provided, just to clean up the backlog of open issues.
