### ISSUE TITLE
Image sequence as input/output

### ISSUE THREAD

**Issue by AndroYD84** [Breakthrough/PySceneDetect#152]
**Description of Problem & Solution**
PySceneDetect can't import/export image sequences, first have to convert image sequences into video and then convert the resulting split videos into image sequences.
It's a convoluted process that wastes time, quality (when using lossy compression) or disk space (when using lossless compression).
Implementing that feature would solve all these 3 problems, actually 4 because the latest PySceneDetect still suffers from the [extra frames](https://github.com/Breakthrough/PySceneDetect/issues/93) problem ending up at the start/end of split videos, with an image sequence is much easier to delete them automatically/manually if you know the pattern.

**Media Examples:**
Splitting the example [goldeneye.mp4](https://github.com/Breakthrough/PySceneDetect/raw/resources/tests/goldeneye/goldeneye.mp4) into scenes using PySceneDetect and ffmpeg version git-2020-01-21-fc6fde2 on Windows 10, I end up getting [one extra frame](https://github.com/AndroYD84/Files/tree/master/PySceneDetectOutput1), it would be much easier to fix that in an image sequence.

**Proposed Implementation:**
Running a command like:
`scenedetect -img IMAGEFOLDER -o OUTPUT detect-content image-sequence`
Would search the IMAGEFOLDER for an image sequence based on how the files were named (ie. frame0001.jpg to frame9000.jpg is a single video made of 9000 frames), then output the scenes in separate directories (ie. ../frame-Scene01/frame0001.jpg to ../frame-Scene01/frame0100.jpg is scene 1, ../frame-Scene02/frame0101.jpg to ../frame-Scene02/frame0200.jpg is scene 2, etc.)
If we end up getting an extra frame and we know the pattern (ie. in my case, the extra frame is at the end of the first scene, then the beginning of every other scene), we can systematically delete the interested frames (ie. frame 100.jpg, frame 101.jpg, frame201.jpg, and so on) automatically.

**Alternative Solutions:**
Or we could simply have a command where we tell PySceneDetect to delete X number of frames at the start and ending of each scenes to avoid the extra frame problem, imagine something like: `scenedetect -img IMAGEFOLDER -o OUTPUT detect-content -r 1 image-sequence` (would remove 1 frame at the beginning and end of every scene).
Even if I ended up erroneously deleting 1-2 frames that weren't an extra frame for every scene, that would still be okay, the tradeoff from having to manually fix the frames and having it done automatically even with that small error margin is totally worth it in my case scenario.

**Comment by Breakthrough** [comment]
Hey @AndroYD84;

OpenCV supports image sequences out of the box.  You should be able to [specify a sequence path](https://stackoverflow.com/a/16713371) as the input video, and PySceneDetect should handle it normally.  The only thing it cannot handle is using an image-sequence combined with the split-video command (as there is no video to split).

Is there a reason to actually specify an output folder for the case of an image sequence, though?  Once you have the frame numbers where the cuts are, you should be able to just use those images directly (or can write a script to put them into subdirectories).

Thoughts?

**Comment by AndroYD84** [comment]
> Is there a reason to actually specify an output folder for the case of an image sequence, though?

Yes, there's a very good reason, when a single folder contains a ginormous amount of pictures (ie. more than 100.000), which is likely to happen when splitting a full movie, any attempt to open it from a file manager (or anything that displays thumbnails) will instantly cripple the entire machine as it tries to generate thumbnails/text for every single of them, when they are split in folders this doesn't happen as the amount of files per folder is reduced significantly (ie. instead of 100.000 frames in 1 folder, you may get 1000 frames in 100 folders), video files already act like "folders" containing multiple frames inside, so they don't suffer from such problem, while image sequences will if they aren't organized properly.
Normally I'd want to check if pyscenedetect is detecting the scenes correctly and look at the output folder from a GUI interface, while the input folder content can be handled entirely from a command-line interface as the content result is usually well known already.

**Comment by Breakthrough** [comment]
Gotcha, the easiest way I can think of to support this would be to add an argument to split-video that indicates if you are using an image sequence or not, for example:

    scenedetect -i my_image_sequence%02d.jpg detect-content split-video --sequence

By default it would just copy each frame from the source directory, but could add an additional option to move them from their original location, e.g.:

    scenedetect -i my_image_sequence%02d.jpg detect-content split-video --sequence --move

Thoughts on the proposed CLI changes?

There *are* some edge cases to keep in mind when implementing this (e.g. having frame numbers not starting from zero, gaps in the sequence, handling the case where creating a new directory fails, or moving an image fails) that I'll need to take into account.  Making good test cases and handling all the potential error cases will be crucial for implementing this feature, which means it'll be a bit more work than I'd like, but I understand your use case and agree it has value.  Will add this to the backlog of proposed features.

In the meantime, you can consider using the `save-images` command to output the first/middle/last frames that PySceneDetect is detecting for ensuring correct detection results (the command allows specifying an output directory).

**Comment by milovan68** [comment]
Hi, thank you for awesome product. I have question about how to open images sequence with python API? I detect timecodes on video with pyscenedetect, after with openCV I parsed video on images (1 in 400ms for FPS=25), if FPS is different from 25, timecode from scenedetect and my parsing images differ. I declined from detect scene from video and want to detect on image sequence, I used example script from documentation, but VideoManager(cv2.Capture('path/to/seq')) except with ValueError: Unexpected element type in video_files list. How to hanlde this? Thank you for answer

**Comment by Breakthrough** [comment]
Hi @milovan68;

I actually just found a bug in the VideoManager preventing image sequences from being loaded.  To answer your question, you should use `VideoCapture(['path/to/seq%04d.jpg'])` for example, however, currently this will result in an error ("Video file(s) not found.").

Re-marking this is a bug, and going to suggest that PySceneDetect should not be responsible for actually doing output of image sqeuences (the output provided by `list-scenes` is sufficient for doing that manually).

**Comment by Breakthrough** [comment]
@AndroYD84, you should not be seeing any extra frames in the latest release (see #93 and #159).  I have re-marked this is as a bug, however, since image sequence _input_ is currently not working.  I'm going to prefer to not have PySceneDetect handle manipulating or copying existing files, as one could write a script to do the same thing using the output of` list-images`.  Thanks!

**Comment by Breakthrough** [comment]
Hi @AndroYD84;

Image sequences will be supported for input in the next release (v0.5.5).  There are still some non-trivial issues that exist with the `save-images` and `split-video` commands, so I'd prefer you create a new issue if you still require supporting copying the respective files to new folders.  I'll remove 'output' from this issue's title just to be clear.

In the meantime, you could write a Python script that uses the output from `list-scenes` to achieve the same thing (if you do, please share as it could be re-used for the feature).

Thanks!
