### ISSUE TITLE
Docs: Edit links are broken

### ISSUE THREAD

**Issue by FichteFoll** [Breakthrough/PySceneDetect#155]
**Bug/Issue Description:**
Doc pages on rtd are missing the repository name in their "Edit this page" URLs.

https://pyscenedetect.readthedocs.io/en/latest/, for example, links to https://github.com/Breakthrough/edit/master/docs/index.md when it should be https://github.com/Breakthrough/PySceneDetect/edit/master/docs/index.md

**Comment by Breakthrough** [comment]
Seems like this is either an issue with ReadTheDocs or my configuration, but definitely an issue.  Thanks for letting me know, will reach out and see if I can find a solution for this.

**Comment by Breakthrough** [comment]
Filed readthedocs/readthedocs.org#7246 to follow up on this.  Marking as in-progress until resolution has been found.

**Comment by Breakthrough** [comment]
Resolved by fdaf3f4739e1b12ca5aa4c6a528cc812a7c9a6a9.
