### ISSUE TITLE
From a VOB file: Not all outputs are visible when doing direct, but works when pre-transcoding

### ISSUE THREAD

**Issue by salamanders** [Breakthrough/PySceneDetect#157]
I tried to split a DVD's VOB file two ways

    scenedetect -i VTS_01_2.mp4 -o ./out detect-content -m 120 -t 40 split-video -c
    scenedetect -i VTS_01_2.mp4 -o ./out detect-content -m 120 -t 40 split-video --high-quality

However, both output ~3 invalid scenes among the ~20 total scenes.  The bad 3, which were the largest, couldn't be opened with VLC.

However, when I pre-transcoded the video, it worked fine!  

    ffmpeg -i VTS_01_2.VOB -c:v libx264 -crf 19 VTS_01_2.mp4  
    scenedetect -i VTS_01_2.mp4 -o ./out detect-content -m 120 -t 40 split-video -c

**Comment by Breakthrough** [comment]
Hey @salamanders;

I'm thinking this is potentially a bug with how OpenCV handles the underlying VOB structure.  To help determine the issue, please add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and attach the generated `BUG_REPORT.txt` file.  If you could provide one for each case (without transcoding & with transcoding) that would be appreciated.

Thanks for the report.
