### ISSUE TITLE
Resize generated images

### ISSUE THREAD

**Issue by Fookiwara** [Breakthrough/PySceneDetect#160]
Is it possible to add an option to save-images so that we can defined the size of the generated images?
Regards,
Phuoc

**Comment by Breakthrough** [comment]
Hi @Fookiwara;

Sure, that sounds like a good idea indeed.  I might need to put some more thought into this for the long term (e.g. selecting scaling method), but I can see this definitely being a nice to have.

Thanks for the idea!
