### ISSUE TITLE
Implement URL as input

### ISSUE THREAD

**Issue by ajeema** [Breakthrough/PySceneDetect#170]
**Description of Problem & Solution**
I am running this on a Django app running on Heroku. I'm using Django-storages to place the users uploaded videos on an S3 bucket. It seems that calling the file back with URL fails because pyscenedetect doesn't accept URL as input.

**Proposed Implementation:**
I would like to see if we can maybe add a flag to tell the app that the source file is coming in as a URL or some conditional check in the video_manager to check if the input is local or remote and handle appropriately

**Comment by Breakthrough** [comment]
Hi @ajeema;

While this is technically possible, I'm not sure if this aligns correctly with where I see the development of PySceneDetect going.  I'd like to avoid having any kind of I/O specific handling logic put into this package, so I'd like to avoid having to make special provisions for URLs.

Is it feasible for your application to write a wrapper which can download the URL into memory or disk, and pass that path to PySceneDetect?

Thank you!

**Comment by ajeema** [comment]
Yes, I can find a work around. Just thought I’d ask as I thought it may be a use case other would run into

**Comment by Breakthrough** [comment]
@ajeema Sounds good, will close this issue until another use case is discovered.

**Comment by ajeema** [comment]
Cheers

**Comment by Breakthrough** [comment]
Hey @ajeema;

This was revisited recently in #188 - sorry for not realizing at the time that this was a duplicate of that one.  URLs should work after the next release (v0.5.5).

You can test it now by checking out the v0.5.5 branch.  I just verified, the following now works:

    scenedetect -i https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4  detect-content

Note that URLs are not compatible with the `split-video` and `save-images` command.
