### ISSUE TITLE
Error: no such option: --threshold

### ISSUE THREAD

**Issue by TzurV** [Breakthrough/PySceneDetect#184]
**Version**: PySceneDetect v0.5.3
**Documentation**: https://pyscenedetect.readthedocs.io/en/latest/examples/usage-example/#finding-optimal-thresholdsensitivity-value

The documentation includes threshold guide baut the help doesn't include such option and following the example results in  
'Error: no such option: --threshold'

**Comment by Breakthrough** [comment]
Hi @TzurV;

The `--threshold` option needs to be used with a detector (i.e. after it), for example:

    scenedetect --input video.mp4 detect-content --threshold 27 split-video

Can you share with me the full command you are trying to run?  Thank you!

**Comment by Breakthrough** [comment]
Closing until response received.  Thank you!
