### ISSUE TITLE
WARNING: scenedetect 0.5.4.1 does not provide the extra 'progress_bar'

### ISSUE THREAD

**Issue by nshtg** [Breakthrough/PySceneDetect#185]
scenedetect is not providing the extra `progress_bar` even though your README still advertises it:

`pip install scenedetect[opencv,progress_bar]`

Running an up-to-date arch linux with python 3.8.5.

**Comment by Breakthrough** [comment]
Good catch, will have to update that as well. Will update the README to match https://pyscenedetect.readthedocs.io/en/latest/download/.

**Comment by Breakthrough** [comment]
Closed by d90cb39411da5365fc4a7a20a86f60bfed56eea8.
