### ISSUE TITLE
Dynamic tqdm size

### ISSUE THREAD

**Issue by master-of-zen** [Breakthrough/PySceneDetect#193]
**Description of Problem & Solution**
Current PySceneDetect bar doesn't resize with console, and have constant width. Which cause huge amount of console spam if console window smaller than original and doesn't increase if it get larger.

**Media Examples:**
<details><summary>Screenshots</summary>

![2020_11_28_15_06_09](https://user-images.githubusercontent.com/46526140/100516264-620a7600-318b-11eb-9c41-6b5acfe17a46.jpg)
![2020_11_28_14_50_41](https://user-images.githubusercontent.com/46526140/100516266-62a30c80-318b-11eb-8dba-cce5201ff79a.jpg)
</details>

**Proposed Implementation:**
Set `dynamic_ncols=True` for all tqdm instance.
From https://github.com/tqdm/tqdm#parameters
```
dynamic_ncols : bool, optional

    If set, constantly alters ncols and nrows to the environment (allowing for window resizes) [default: False].
```

**Comment by Breakthrough** [comment]
Resolved in 998ff11303691521f6733b5995cef6c2d4bb1781 in branch v0.5.5, will be included in next release of PySceneDetect.

Thanks for the bug report!
