### ISSUE TITLE
[Question] Apply find_scenes method in python only on a specific duration of video + or on list of video frames

### ISSUE THREAD

**Issue by ahkarami** [Breakthrough/PySceneDetect#194]
Thanks for the repo.
I have two questions:
1- How one can apply `find_scenes` method in **python** only on a specific duration of video (not all of the frames of the video)? (e.g., from its 00:01:00 up to 00:05:00) 
2- How one can apply `find_scenes` method in python on a list of video frames (_i.e.,_ instead of passing a video path, for example pass a list of video frames in numpy array format (which for example read them previously via OpenCV))?

**Comment by Breakthrough** [comment]
Hi @ahkarami;

To answer your questions:

1. Call `set_duration()` with both start_time and end_time set ([see the documentation on set_duration for details](https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api/video_manager.html#scenedetect.video_manager.VideoManager.set_duration)).
2. You may want to implement your own VideoManager that performs the same actions as a regular VideoManager, but uses your underlying buffer of video frames.  If you are using the `find_scenes` API directly, you should just need to implement `read`/`retrieve`/`grab`, which align 1:1 with the respective OpenCV VideoCapture API calls.

Does this answer your questions?  Thank you!

**Comment by ahkarami** [comment]
Dear @Breakthrough,
Thank you for your complete answer.
