### ISSUE TITLE
Changelog on readthedocs.io needs updating

### ISSUE THREAD

**Issue by jeremymeyers** [Breakthrough/PySceneDetect#200]
the most recent version is 0.5.5 on there

**Comment by Breakthrough** [comment]
Hey @jeremymeyers;

v0.5.5 was released yesterday, and is the most recent version, so that is expected... Or do you mean something else?

Thanks!

**Comment by jeremymeyers** [comment]
Ugh this is totally based on a misread on my part. nvermind!
