### ISSUE TITLE
"illegal hardware instruction" error on Apple Silicon

### ISSUE THREAD

**Issue by cstelmach** [Breakthrough/PySceneDetect#204]
**Bug/Issue Description:**
"illegal hardware instruction" error on all scenedetect commands on Apple Silicon Mac (OSX 11.1).

**Required Information:**
```
❯ scenedetect help
zsh: illegal hardware instruction  scenedetect help

❯ scenedetect -v debug -l BUG_REPORT.txt help
zsh: illegal hardware instruction  scenedetect -v debug -l BUG_REPORT.txt help
```

**Comment by Breakthrough** [comment]
Hi @cstelmach;

Could you try disabling Rosetta and see if that works?  ([link](https://stackoverflow.com/a/65430822))

I'm assuming this is due to the OpenCV package from pip - could you also try uninstalling that and seeing if you can run the `scenedetect` command afterwards?

Thanks!

**Comment by cstelmach** [comment]
Hi @Breakthrough.
It was the numpy package. Now everything is working as it should. Thanks :)
