### ISSUE TITLE
Frame image save fail

### ISSUE THREAD

**Issue by kimlia545** [Breakthrough/PySceneDetect#214]
I converted the file and used it
.mkv -> .mp4

Writing 38559 frames to CSV...
257 scenes detected!
[h264 @ 000002801b12de40] mmco: unref short failure
[h264 @ 000002801b12de40] mmco: unref short failure
[h264 @ 000002801b12de40] mmco: unref short failure
[h264 @ 000002801b12de40] mmco: unref short failure

**Comment by Breakthrough** [comment]
Can you share some additional information?  What is the command you are invoking?  Can you share the video?  How did you convert the file?

Thanks!
