### ISSUE TITLE
min-scene-len does not work

### ISSUE THREAD

**Issue by haofanwang** [Breakthrough/PySceneDetect#215]
**Bug/Issue Description:**
--min-scene-len does not work in the newest version ('v0.5.5'), but it works well in v0.5.4

**Required Information:**
To reproduce the error,
`scenedetect --input xx.mp4 --output xx detect-content --min-scene-len 3.0s split-video`

**Comment by Breakthrough** [comment]
Hey @haofanwang;

`--min-scene-len` was changed to a global option.  You should now specify it before `detect-content, e.g.:

    scenedetect --input xx.mp4 --output xx --min-scene-len 3.0s detect-content split-video

Does this resolve the issue?

Thanks!

**Comment by haofanwang** [comment]
Thanks
