### ISSUE TITLE
Scene Detection Issue

### ISSUE THREAD

**Issue by RustX2802** [Breakthrough/PySceneDetect#219]
I’m trying to detect the scenes of two clips:

```
cap = cv2.VideoCapture(‘first.mp4’, 0)

scene_manager = SceneManager()

scene_manager.add_detector(ContentDetector(threshold=30.0))

cap2 = cv2.VideoCapture(‘second.mp4’, 0)

scene_manager2 = SceneManager()

scene_manager2.add_detector(ContentDetector(threshold=30.0))

if (cap.isOpened()== False):

print(“Error opening video stream or file”)

if (cap2.isOpened()== False):

print(“Error opening video stream or file”)

src_image = scene_manager.detect_scenes(cap)

src_image_example = cv2.cvtColor(src_image, cv2.COLOR_BGR2RGB)

tar_image = scene_manager2.detect_scenes(cap2)

tar_image_example = cv2.cvtColor(tar_image, cv2.COLOR_BGR2RGB)
```
However, I get the following error:

```
error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function ‘cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = (cv::impl::::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]’
Unsupported depth of input image:
‘VDepth::contains(depth)’
where
‘depth’ is 6 (CV_64F)
```
Looking at the tutorial SceneManager — PySceneDetect v0.5.5 documentation
I think my issue is that SceneManager.detect_scenes() just returns an int representing how many frames have been processed, but

`cv2.cvtColor()`
is expecting to be passed an image, or a numpy array.

Is there any way how I can overcome this issue?

Thanks in advance!

**Comment by Breakthrough** [comment]
Hey @RustX2802;

What are you trying to accomplish here?

You might want to reference [the API documentation](https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api/scene_manager.html#scenedetect.scene_manager.SceneManager.detect_scenes) - `detect_scenes()` returns the number of frames it processed.

Are you looking to obtain the frame where a scene change occurs?  If so, you'll want to pass a callback function to `detect_scenes`, which will get called with the frame # and image when a scene change occurs.

Does this help?  Thanks!

**Comment by RustX2802** [comment]
Hey @Breakthrough ;

Exactly, I want to obtain only those frames that trigger the scene change. And then make some operations on them.
I got your point. Thanks for your feedback. I will try it.

**Comment by RustX2802** [comment]
Hey @Breakthrough ;

The issue seems to persist on after passing a callback function to `detect_scenes`. Here is my update:

`cap = cv2.VideoCapture('first.mp4', 0)
fps = cap.get(cv2.CAP_PROP_FPS)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration = frame_count/fps
frame_seq = duration*fps-1
frame_no = (frame_seq/(duration*fps))
scene_manager = SceneManager()
scene_manager.add_detector(ContentDetector(threshold=30.0))
cap2 = cv2.VideoCapture('second.mp4', 0)
scene_manager2 = SceneManager()
scene_manager2.add_detector(ContentDetector(threshold=30.0))

while(cap.isOpened()|cap2.isOpened()):
  cap.set(cv2.CAP_PROP_POS_FRAMES, frame_no)
  ret, frame = cap.read()
  ret2, frame2 = cap2.read()
  if ret == True and ret2 == True:
    src_image = scene_manager.detect_scenes(cap, callback=(frame, frame_no))
    src_image_example = cv2.cvtColor(src_image, cv2.COLOR_BGR2RGB)`

and same error:

`error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function ‘cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = (cv::impl::::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]’
Unsupported depth of input image:
‘VDepth::contains(depth)’
where
‘depth’ is 6 (CV_64F)`

**Comment by Breakthrough** [comment]
Also have a look at [`FakeCallback` and `test_detect_scenes_callback(...)` here](https://github.com/Breakthrough/PySceneDetect/blob/v0.5.6/tests/test_scene_manager.py#L190-L228) for a more detailed example.
