### ISSUE TITLE
error when split video

### ISSUE THREAD

**Issue by herokarimpoor** [Breakthrough/PySceneDetect#221]
hi
when I split video I have a below problem?
![Screenshot from 2021-05-29 10-10-53](https://user-images.githubusercontent.com/52469283/120059357-5b8b8700-c066-11eb-81e1-cfc03d9c5b6c.png)

**Comment by Breakthrough** [comment]
Hi @herokarimpoor;

It looks like the version of `ffmpeg` you are using was compiled without x264 support (see `--disable-libx264` in the output).  See [this answer on StackOverflow](https://stackoverflow.com/a/20036192) for more details.  I would recommend trying to update `ffmpeg` to a newer version of the package, or see if installing `libavcodec-extra` helps.

Alternatively, you can override the arguments passed to the split-video command to use a different codec, or use stream copy mode (by passing `--copy` to `split-video`).

Hope this helps, let me know how you resolve it.

**Comment by herokarimpoor** [comment]
Thank you for your reply
