### ISSUE TITLE
detect-adaptive

### ISSUE THREAD

**Issue by wanghaisheng** [Breakthrough/PySceneDetect#229]
```
This means we need to use content-aware detecton mode (`detect-content`) or adaptive mode (`detect-adaptive`)
```
 there is doc about adaptive mode,but the latest code seems still not support that yet ?

**Comment by wjs018** [comment]
This is a detector that is slated for a future release and it seems as though a reference snuck into the docs a bit early. If you want to try out the detector, it is live on the [0.5.6 branch](https://github.com/Breakthrough/PySceneDetect/tree/v0.5.6). You can see the code for the detector [here](https://github.com/Breakthrough/PySceneDetect/blob/v0.5.6/scenedetect/detectors/adaptive_detector.py).
