### ISSUE TITLE
Splitting Clips

### ISSUE THREAD

**Issue by rhefner1** [Breakthrough/PySceneDetect#23]
Hey @Breakthrough, thanks for this great project. I've been processing some clips and the scene detection seems right on. My project is detecting the scenes in an AVI file and splitting them into separate clips. The docs seem to hint that the detection CSV can be passed to `ffmpeg` or something, but I can't for the life of me figure out how to do that.

Is this easy to do or should I write a little Python wrapper that calls `ffmpeg` in a subprocess?

Specifically, I'm looking at [this part of the docs](https://github.com/Breakthrough/PySceneDetect/blob/master/docs/examples/usage-example.md#splittingcutting-video-into-clips) that is empty.

Thanks!

**Comment by Breakthrough** [comment]
I've been meaning to add this to PySceneDetect for a while, but the OpenCV video encoding options are rather limited (only letting you select a codec, and nothing else, not even bitrate).

One quick tool you can use for this is mkvmerge-gui or mkvtoolnix-gui, and copy/paste the comma-separated timecodes into the file splitting section.  This doesn't reencode the video, just re-muxes it.

For ffmpeg, there's command line flags to set the start/end/duration of the input, copying the video container.  This should achieve the same results as using mkvtoolnix, although I think you would have to make a call to ffmpeg for each scene you wanted to extract from the input file.

**Comment by rhefner1** [comment]
@Breakthrough: I just did a test with both mkvmerge with the command you provided and mkvtoolnix-gui and both worked perfectly!

I'm splitting up some home movies and a few years ago had tried doing it manually but gave up. All I have to do here is write a little Bash script and it's done. Thanks for the help and the great tool!

**Comment by Breakthrough** [comment]
@rhefner1 glad you're finding it useful, that reminds me I have some older home video footage I need to apply this to myself.

Thanks again for your feedback, I've updated [that particular section](https://github.com/Breakthrough/PySceneDetect/blob/master/docs/examples/usage-example.md#splittingcutting-video-into-clips) of the documentation (if you think this should be mentioned anywhere else, feel free to let me know).

**Comment by rhefner1** [comment]
:+1: thanks!

**Comment by Breakthrough** [comment]
Hey @rhefner1;

One last update for you, I managed to integrate calling mkvmerge into the latest version of PySceneDetect (v0.4), so now when the `-o` option is specified, the input video will be split into individual scenes (albeit as .mkv format).

 - Brandon

**Comment by rhefner1** [comment]
@Breakthrough that's fantastic. Thanks for your work!
