### ISSUE TITLE
downscale_factor()

### ISSUE THREAD

**Issue by ajeema** [Breakthrough/PySceneDetect#237]
I have noticed a speed increase with downscale_factor. However, my question is does this do anything to the source file or is the downscale_factor held in memory? Tried looking through the code to see what it was doing but couldn't find anything

**Comment by Breakthrough** [comment]
Hey @ajeema;

You can find the actual spot where it gets used here in VideoManager:
https://github.com/Breakthrough/PySceneDetect/blob/v0.5.5/scenedetect/video_manager.py#L783

Note that in v1.0, the responsibility for downscaling is being moved to the SceneManager, but the overall usage will remain the same.

Is this what you were looking for?  Thanks!

**Comment by Breakthrough** [comment]
Note that in v0.6 this has been moved to SceneManager, and is done in `_decode_thread`:
https://github.com/Breakthrough/PySceneDetect/blob/b89238c/scenedetect/scene_manager.py#L811
