### ISSUE TITLE
Unable to run scenedetect on bluemix cf app

### ISSUE THREAD

**Issue by yashgoyalMIT** [Breakthrough/PySceneDetect#24]
I am running a python flask app on bluemix. The code runs perfectly well on local machine( macbook pro) but for some reason I am unable to run it on bluemix. Error is shown below:

`TypeError: 'int' object is not iterable
`

The reason I am getting this error is because opencv-python which is being installed (via pip) does not support ffmpeg and thus it is unable to run this line of code.

```
cap = cv2.VideoCapture(video_file_path)
cap.isOpened()
```
returns false

Any solution for this?

**Comment by AKSHAYUBHAT** [comment]
Try installing python-opency using os package manager like APT or yum

**Comment by yashgoyalMIT** [comment]
For some reason `sudo apt-get` does not work on bluemix (Access issues) and simple `apt-get` is being skipped.

**Comment by AKSHAYUBHAT** [comment]
You should be able to sudo. https://developer.ibm.com/answers/questions/187174/virtual-images-cannot-sudo-within-a-ubunutu-image.html

**Comment by kartikarora** [comment]
I'll elaborate what @yashgoyalMIT was trying to say. 

We are using cloud foundry to deploy the flask app on bluemix. Cloud foundry skips the `apt-get` command, hence `python-opencv` does not get installed.

**Comment by AKSHAYUBHAT** [comment]
You should find a the correct "buildpack"  which contains OpenCV, without it it wont run. 
There is also a possibility that your platform (if its similar to Google App Engine) limits any compiled C/C++ python modules, in which case you cannot use OpenCV.

**Comment by Breakthrough** [comment]
It's usually best in the cases where you can't obtain a Linux package to compile OpenCV from source, rather than use the `pip` builds.

Are you able to build OpenCV from source locally?  If you have a machine that matches the server architecture, you may have better luck compiling the OpenCV Python module locally, and installing that version on your server via `pip` (albeit specifying the path to the compiled module).

**Comment by yashgoyalMIT** [comment]
I am able to build OpenCV from source locally but the problem comes up when I try the same on Bluemix Cloud Foundry App. The build fails on `sudo make install` due to access issues.

**Comment by kartikarora** [comment]
@Breakthrough Thanks for the reply. We were able to compile the OpenCV with ffmpeg and the python bindings for it using your docs [here](https://breakthrough.github.io/Installing-OpenCV/). Worked like a charm on our local machines (Ubuntu 16.04 64bit, the server is ubuntu 14.04 64bit)

We then tried to do the same on the linux server and the cloud foundry container on it. Since it's a cloud infrastructure, we don't have sudo rights, hence `sudo make install` fails. Moreover, the container itself doesn't have sudo rights. 

I have been trying to get help on their slack team as well, they are suggesting building ffmpeg first, then opencv, then the python bindings from source itself and not use sudo. This raises an issue of building and installing ffmpeg and opencv, without `sudo`!

**Comment by Breakthrough** [comment]
@kartikarora in that case, you might want to look into installing the binaries only locally, in a path you have permissions.  The actual folder to place them in depends on your distribution, but can be set when calling cmake before building (via the  `-D CMAKE_INSTALL_PREFIX=/usr/local` option).  There are other build flags you can configure to specify the paths to the various required libraries, if you can't install them system-wide either (see [this page](http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html) for details).

Once the install prefix is configured to a folder you have write permissions to, you should be able to call `make install` without the `sudo` prefix.  From there, you could install the compiled Python module (which should be copied to the install directory after calling `make install`) using `pip`.  Combining `pip` with the `--user` flag allows you to install the Python module only for the local user, and thus does not require `sudo`.

**Comment by Breakthrough** [comment]
@kartikarora / @yashgoyalMIT any luck using the `cv2.so` module you compiled?

**Comment by kartikarora** [comment]
@Breakthrough I've been trying to put all the `cv2.so` to virtual environment's site-packages and the shared libraries into CloudFoundry's `LD_LIBRARY_PATH`. So far I've been successful with putting opencv and ffmpeg's `.so` files. But it seems there are more files which I need to put there.

@yashgoyalMIT tried building a docker image of our local system and upload it on a container. He has been successful in building and running it. Now we looking into scaling it and running our flask app behind an apache/nginx server to bind the app to multiple ports and for load balancing.

**Comment by yashgoyalMIT** [comment]
@Breakthrough The only way I could get this to work was by building a docker image with all the dependencies for the flask app and then deploying it to IBM Bluemix container service  which runs the docker containers in a hosted cloud environment on IBM Bluemix.  This is what my **Dockerfile** looks like:

```
FROM ubuntu:latest

COPY requirements.txt /flask-app/requirements.txt

RUN apt-get update -y
RUN apt-get install -y python-pip libffi-dev libssl-dev python-dev build-essential python-setuptools

COPY . /flask-app
WORKDIR /flask-app

RUN apt-get install python-opencv -y
RUN pip install -r requirements.txt
RUN apt-get install ffmpeg -y

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["restapi.py"]
```

Advantages of this approach is that I have more control over my application but there is one downside that the whole delivery pipeline is slower as compared to cloud foundry app delivery pipeline even when all the build steps are cached in the next cycle. The delay is mostly on Bluemix's end.

Either ways the **issue is resolved**. Thanks a lot for the support.

**Comment by Breakthrough** [comment]
@yashgoyalMIT glad you found an approach to resolve the issue, using a Docker container seems like a novel approach (although as you mentioned, deployment will be a lot slower in that regard).  Thanks again for your submission & feedback :)
