### ISSUE TITLE
Results in MSU Video Shot Boundary Detection Benchmark

### ISSUE THREAD

**Issue by AleksandrGushchin** [Breakthrough/PySceneDetect#241]
Hello,
we recently launched and evaluated this algorithm in our [new benchmark](https://videoprocessing.ai/benchmarks/sbd.html).

It takes 5th place by F1 score and 1st by FPS. You can see the results [here](https://videoprocessing.ai/benchmarks/sbd.html#leaderboard).

If you have any other SBD method you want to see in our benchmark, we kindly invite you to participate.
You can submit it for the benchmark, following the [submission steps](https://videoprocessing.ai/benchmarks/sbd.html#how_to_submit).

**Comment by Breakthrough** [comment]
Hi @AleksandrGushchin;

This is awesome :)

Would you be able to let me know what command line arguments you are using with PySceneDetect?  I'm curious if you used just `detect-content`, or a combination of `detect-content` (cut-transitions) and `detect-threshold` (fade transition).  Also, were any threshold values tuned for the data set, or were the defaults used?  (The large dataset you are using would be ideal for tuning the default values we ship with PySceneDetect)

Lastly, a new detector was added in the latest version of PySceneDetect called `detect-adaptive` which handles fast camera movement better.  It can be used as a drop-in replacement for `detect-content`.

Thanks so much for reaching out, this is awesome work!  👍

**Comment by Breakthrough** [comment]
Have followed up with the authors via private correspondence.
