### ISSUE TITLE
Scenes.csv file should not include "Timecode List"

### ISSUE THREAD

**Issue by eksperimental** [Breakthrough/PySceneDetect#243]
I think having it breaks the purpose tabulated data, as it has an irregular number of columns.
I think I additional file named "*.TimecodeList" containing either one line comma separated, or one timecode per line.

**Comment by eksperimental** [comment]
Additionally, the Timecode List:  string is missing the initial entry with timecode: 00:00:00.000
This is how it is shown now,
`Timecode List:,00:00:03.440,`...

**Comment by Breakthrough** [comment]
This was discussed [here in #136](https://github.com/Breakthrough/PySceneDetect/issues/136#issuecomment-761883299) - you can call `list-scenes -s` to skip the first row.

This row was intended for mkvmerge, which accepts the timecodes where a new video should be created (see docs for `--split` at https://mkvtoolnix.download/doc/mkvmerge.html).
