### ISSUE TITLE
Frame Number Zero is missing in Stats with detect-content

### ISSUE THREAD

**Issue by eksperimental** [Breakthrough/PySceneDetect#244]
The stats start at frame no. 1

**Comment by Breakthrough** [comment]
This is expected, since there can be no stats calculated for frame 0, since statistics are measured by the delta of the current frame from the previous frame.

**Comment by eksperimental** [comment]
> This is expected, since there can be no stats calculated for frame 0, since statistics are measured by the delta of the current frame from the previous frame.

detect-content is the only one that does not show this frame. The rest do

**Comment by Breakthrough** [comment]
Correct, detect-threshold has the average of the current frame.  detect-content has only the delta from the previous frame, so there is no number for frame 0.

**Comment by eksperimental** [comment]
> Correct, detect-threshold has the average of the current frame. detect-content has only the delta from the previous frame, so there is no number for frame 0.

 I noticed this when I read your answer in my first Issue. Thank you
