### ISSUE TITLE
PySceneDetect is not giving accurate results

### ISSUE THREAD

**Issue by AhmedEwis** [Breakthrough/PySceneDetect#245]
Hello, 
Why PySceneDetect is giving the timeline for scenes more than the original script?
Like for example, I have "x" movie which has 305 scenes from the original pdf script from IMDB.
But when I run the PySceneDetect, it gave me 1512 scenes which are not matching with the IMDB script.
I need to know what I am missing? and how can I make it aligned with the original script?

**Comment by Breakthrough** [comment]
Can you provide an example of the script format you're using, and what you mean by # of scenes?

PySceneDetect detects shot changes, not "scenes" in the sense of a contiguous set of cuts representing part of a story.

**Comment by AhmedEwis** [comment]
Hi, thanks for your reply.
In the first photo, it shows the number of scenes is only 314 scene in the movie according to the original script from IMDB.
![1](https://user-images.githubusercontent.com/65680238/135994285-4f310b3f-829e-4626-857b-ffd72ed1aa83.PNG)
However, when I applied the PySceneDetect, it shows the number of scenes is 1513 scenes.
![2](https://user-images.githubusercontent.com/65680238/135994508-8396db52-1325-4e8d-841f-16ece7128a7b.PNG)
Is there any way to make pyscene detect only according to the script from IMDB? how they can be aligned?

**Comment by wanghaisheng** [comment]
for my understanding  all 3 algorithm in pyscenedetect  only detect frame changes for futher cutting. it does not concern about the content in the frame /scene you wanted , whether sky or character in this scene.
since you actually want to cut videos into parts according to scene content  (one is the scene image in thousands frame,one is the scene script in words description format acting as annotation for the frame)
what openai  clip model can do is mapping scene frame image between a word description. 
this is the underlying logic i put here .in my opinion,  you need a branding new algorithm to achieve your purpose.
@AhmedEwis

**Comment by Breakthrough** [comment]
@wanghaisheng that is correct, currently we only detect individual shot boundaries.  Any association of cuts into a "scene" still needs to be done by something else downstream.  You can see examples of this here: https://pyscenedetect.readthedocs.io/en/latest/other/literature/

On the homepage, it should say "PySceneDetect is a command-line application and a Python library for detecting ~scene~ **shot** changes in videos, and automatically splitting the video into separate clips."

**Comment by Breakthrough** [comment]
When calling `detect_scenes` on a SceneManager, you can provide a callback that gets invoked on each new cut:
https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api/scene_manager.html#scenedetect.scene_manager.SceneManager.detect_scenes

There's a short example [here on #5](https://github.com/Breakthrough/PySceneDetect/issues/5#issuecomment-670956263).

Of course you can just [use the regular API](https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api.html#example) and process the frame numbers after manually like [in `tests/api_test.py`](https://github.com/Breakthrough/PySceneDetect/blob/master/tests/api_test.py).  Hope this helps, thanks.
