### ISSUE TITLE
Decrease default threshold from 30 -> 27

### ISSUE THREAD

**Issue by Breakthrough** [Breakthrough/PySceneDetect#246]
The default threshold (currently 30) should be lowered by 10% to achieve better accuracy for most inputs.

The current default was chosen as a nice round number, based on my own tests with a very small/limited dataset.  As per https://videoprocessing.ai/benchmarks/shot-boundary-detection.html they kindly repeated the benchmark with the default threshold (t = 30) and a value 10% lower (t = 27).  The latter value achieved much greater accuracy on the entire training set, which is fairly robust.

**Comment by Tetsujinfr** [comment]
Yes true, threshold=27 just worked better on most videos that I did test.
Thanks for the informed tip!

**Comment by CyberLykan** [comment]
What about regular threshold detection (not content)? Would the optimal value be 12 or something different?

**Comment by Breakthrough** [comment]
@CyberLykan good point, that was also just a guess based on some sample footage I created.  The value could likely be raised higher to detect the fades earlier, but I think 12 is a pretty safe bet for most use cases.  If anyone has a collection of samples that could be used as a heuristic though that would also be great.

**Comment by Breakthrough** [comment]
@Tetsujinfr have you had an opportunity to test `detect-adaptive`?  I'm curious if that works better for you, and if so, what parameters you end up using.  Thanks!
