### ISSUE TITLE
Circular references

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [Breakthrough/PySceneDetect#25]
you have several circular references where you are importing scenedetect within itself.
you can just use "import manager" rather than import scendetect.manager", etc.

In some cases there is no need to import scenedetect 
https://github.com/Breakthrough/PySceneDetect/blob/master/scenedetect/manager.py

**Comment by Breakthrough** [comment]
Hello @AKSHAYUBHAT;

PySceneDetect strives to follow the Google Python Style Guide as closely as possible.  Under this convention, absolute imports are preferred against relative imports (see [the Packages section](https://google.github.io/styleguide/pyguide.html#Packages)).

However, the reference you pointed out in `manager.py` is indeed unnecessary in the context.  I've recently started going through some of my other projects (e.g. [DVR-Scan](https://github.com/Breakthrough/DVR-Scan)) with a PyLinter, so I will apply the same process to PySceneDetect, which should detect these cases.

Thank you for the submission, I will close this issue after the relevant code changes have been committed.

**Comment by Breakthrough** [comment]
As an update to this issue, I plan on having this closed for the release of PySceneDetect v0.5.  When the relevant changes have been made, I will mark this as fixed.  Feel free to bring any further comments/issues that are noted to my attention, either here, or in a new issue (depending if the new release is out yet or not).

**Comment by Breakthrough** [comment]
This has been fixed in the release of v0.5-beta and will be included in the release of v0.5 sometime this month.  Thank you for your submission, and helping to make PySceneDetect even better!  👍
