### ISSUE TITLE
Added a link to 'PySceneDetect in Literature'

### ISSUE THREAD

**Issue by Tsunehiko** [Breakthrough/PySceneDetect#251]
Thanks to PySceneDetect! I have used PySceneDetect in this [research](https://ieeexplore.ieee.org/abstract/document/9522986). I also fixed the errors I encountered in the research by myself and created a pull request #250. I will continue to use PySceneDetect in the future work.
I would appreciate it if you could add a link to the paper.

**Comment by Breakthrough** [comment]
Glad you found it useful!  Will be happy to include a link to the paper :)
