### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by AhmedEwis** [Breakthrough/PySceneDetect#253]
Hi. 

I am running the below code as per the given instructions from: 

https://pyscenedetect.readthedocs.io/en/latest/examples/usage-example/

My code is:

![image](https://user-images.githubusercontent.com/65680238/145687765-e09bf2aa-5184-4d26-ba72-d5a004817061.png)

**Comment by Breakthrough** [comment]
@AhmedEwis you need to follow the Python example:
https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api.html#example

What you have there is the command line example.  Hope this helps, thanks.

**Comment by Breakthrough** [comment]
You can also access the save-images command from the scene_manager module:
https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api/scene_manager.html#scenedetect.scene_manager.save_images

**Comment by AhmedEwis** [comment]
@Breakthrough  Thanks for your support.
I have already used the ContentDetector example and got the scenes results.
But, how to get the CSV stats file as mentioned below: 

![image](https://user-images.githubusercontent.com/65680238/145721194-10f2e7ad-2d3a-4818-93eb-f331bd310974.png)

**Comment by Breakthrough** [comment]
Follow what's in api_test.py; in particular, you need to call `save_to_csv` on a StatsManager:
https://github.com/Breakthrough/PySceneDetect/blob/master/tests/api_test.py#L107
