### ISSUE TITLE
Using an inmemory Bytestream (io.BytesIO object) as videoinput

### ISSUE THREAD

**Issue by scuba14** [Breakthrough/PySceneDetect#257]
**Description of Problem & Solution**

I am using a scraper which is downloading and processing videos. While downloading the videos are stored into io.BytesIO objects which are hold im memory by python. The problem is that I can not pipe this Bytestream into PySceneDetect because the Videomanager class is based on OpenCV VideoCapture class. 
A fix would be to write the videos to a disk or to a temporary file but thats not the sense of pipeline processing  .
 
A solution would be to change the video_manager class so it can also accept inmemory BytesIO objects or os-Pipeline Inputs. 
Maybe I am missing something and its already possible but with the change of the video_manager class the following would be possible:

1. Process video with ffmpeg etc ... --> stdout Pipe/ named Pipe
2. Read Video from stdout in io.BytesIO
3. Make a scene detection on io.BytesIO or directly from step 1 (stdout Pipe/ named Pipe)
4. Get Scenes from PySceneDetect and apply them on the video hold im meory (io.BytesIO)
5. Do some other pipeline stuff without writing the video to a file ...

This functionality could even go further and a livestream captured with ffmpeg could be live processed and scene detected thanks to: https://github.com/Breakthrough/PySceneDetect/issues/5

**Solution**:

Implement stdin pipe and/or BytesIO support in video_manager class

**Comment by Breakthrough** [comment]
This may be possible once #213 is implemented via PyAV:

https://pyav.org/docs/stable/api/_globals.html#av.open

> Parameters: file (str) – The file to open, which can be either a string or a file-like object.

That should work for your use case, although I have not tested it myself yet.  Hope this helps for now!

**Comment by Breakthrough** [comment]
I just did a quick test and this does seem to work with the new VideoStreamAv backend.  I'll add a constructor parameter to allow this to work for v0.6.

**Comment by Breakthrough** [comment]
Will be included in v0.6 release.  Added tests to demonstrate example usage:
https://github.com/Breakthrough/PySceneDetect/blob/v0.6/tests/test_backend_pyav.py
