### ISSUE TITLE
Compatibility with OpenCV major version 4

### ISSUE THREAD

**Issue by BarRozenman** [Breakthrough/PySceneDetect#260]
**Bug/Issue Description:**
It would be nice if an update for support in OpenCV major version 4 (that has been available since [Jan 9, 2019](https://pypi.org/project/opencv-python/4.0.0.21/))
this could help using [PySceneDetect](https://github.com/Breakthrough/PySceneDetect) on an existing  environment (with OpenCV 4) and not be forced to create a custom environment for PySceneDetect specifically

**Expected Behavior:**
Compatibility with OpenCV major version 4.

**Comment by Breakthrough** [comment]
Hi, I'm not sure what you mean?  PySceneDetect should work with both OpenCV 3 and 4.  Why are you forced to create a custom environment?

**Comment by BarRozenman** [comment]
sorry there must be some other issue with my OpenCV installation, the issue was solved by reinstall OpenCV

**Comment by Breakthrough** [comment]
In the future if you run into any issues feel free to post logs here so we can get it sorted out.

Thanks for the update!
