### ISSUE TITLE
v0.6 Beta Release & Feedback

### ISSUE THREAD

**Issue by Breakthrough** [Breakthrough/PySceneDetect#262]
PySceneDetect v0.6 is now in ~beta~ release candidate, including performance improvements and major API updates - see [the new Quickstart guide](http://manual.scenedetect.com/en/v0.6/api.html#quickstart) (feedback is welcome!).  You can install the beta from pip:

    pip install --upgrade --pre scenedetect

Or downloading [a portable .exe version for Windows](https://github.com/Breakthrough/PySceneDetect/releases/download/v0.6-rc0/PySceneDetect-0.6-rc0-win64-portable.zip).  You can also download a .whl or .exe directly from the [latest builds on AppVeyor](https://ci.appveyor.com/project/Breakthrough/pyscenedetect/history) (go to the latest successful build, click on any Python version, and go to Artifacts).

Links:
 - API/CLI Docs: http://manual.scenedetect.com/en/v0.6
 - Updated Site: http://scenedetect.com/en/v0.6
 - Changelog & Release Notes: https://github.com/Breakthrough/PySceneDetect/releases/tag/v0.6-rc0)

In addition to bug reports, please post any feedback on the new API changes, configuration file support, and performance changes.  Owners of existing packages relying on `scenedetect` should pin their project to < 0.6 and prepare for the upcoming changes, however the final release will include some degree of backwards compatibility with v0.5 to avoid breaking most applications.

Known Beta-Only Issues
--------------------------------------------------

Issues only affecting the v0.6 beta.  Checkmark indicates done and ready for next beta release. v0.6-dev4 will be the final beta release.

 - [X] Fix hang when using `--backend pyav` on Linux when program quits
     - Must manually enable multithreading mode now using [a config file](http://scenedetect.com/projects/Manual/en/v0.6/cli/config_file.html) option (set `threading-mode = auto` under `[backend-pyav`])
 - [x] Quality set when using `save-images` is ignored, always set to 95 for JPEG and 100 for WebP

See [the changelog](https://github.com/Breakthrough/PySceneDetect/blob/v0.6/docs/changelog.md) for a full list of known issues.

**Comment by camjac251** [comment]
I'm trying this out on Windows 11 with an anaconda environment (With python 3.7, tried 3.6 too) but when I install `av`, PySceneDetect still shows the message below. I've tried installing `av` through conda and through pip, in fresh environments, but both ended up showing the same message
```
[PySceneDetect] Failed to read any frames from video file. This could be caused by the video having multiple audio tracks. If so, try installing the PyAV backend:
      pip install av   
```

**Comment by Breakthrough** [comment]
Hey @camjac251;

Thanks for the suggestion, I will make a note to address that in #213 before releasing v0.6.  In the meantime, you can [create a `scenedetect.cfg` file](http://scenedetect.com/projects/Manual/en/v0.6/cli/config_file.html) and set `backend = pyav` to override the default backend automatically.

Many thanks for trying out the beta, much appreciated - happy to hear any other feedback or issues you run into.

**Comment by camjac251** [comment]
I don't think I was able to get `pyav` working. I set `-b pyav` in my commandline and was trying out
`FOR /F "tokens=*" %G IN ('dir /b *.mkv') DO scenedetect -i "%G" -o D:\pyscenedetect\all detect-content split-video -a "-hwaccel auto -c:v libx264 -preset ultrafast -crf 0 -an -sn"`, and on the first one it was  trying. It would just show 0 being the current position of the file, and not advance. This was with a video file with blu-ray specs (h264, rec709, a few audio tracks with dts-hd ma, subtitles)

**Comment by Breakthrough** [comment]
@camjac251 thanks for the heads up - I was able to reproduce the same issue locally with another Blu-ray file, so will need to do some debugging here.  Seems to be some issue with the multithreaded decoding.  Will update the beta as soon as I can get this sorted out.

**Comment by Breakthrough** [comment]
@camjac251 Alright I've figured out the issue, it was actually due to the progress bar.  There seems to be an issue calculating the length of the video, which erroneously causes the progress bar to not be updated.

Processing should still work, just the progress bar won't be updated until it is completed.  Will let you know when a fix is available, thanks!

**Comment by camjac251** [comment]
That was extremely fast, thank you!

**Comment by Breakthrough** [comment]
Just a heads up, the latest beta (v0.6-dev3) may have an issue with the PyAV backend that causes processing to not complete.  It seems this is due to the new threading mode changes, but I am having trouble reproducing the issue locally (it only seems to fail under Linux on Python 3.6, 3.8, and 3.9, but not 3.7).  I was unable to reproduce the issue under WSL with Python 3.8 so will setup a VM with the same build environment as the server.

In the meantime, if anyone runs into this issue, if you could provide debug logs for analysis that would be most helpful.  Thanks!

**Comment by Breakthrough** [comment]
@camjac251 is the latest beta working out for you with PyAV?

I ran into a lot of problems fixing the deadlock issue on Linux - the solution that's in place now seems to be working so far, but I'm reluctant to use PyAV as the default because of it.  Can you share your feedback or if you experienced any deadlocks on Windows?

I have not had any lockups on Windows, but want some more feedback before allowing it as a default value.  If it seems more stable on Windows then might make this a Windows-specific default until there's more coverage/feedback from Linux users.

Thanks!

**Comment by camjac251** [comment]
> @camjac251 is the latest beta working out for you with PyAV?
> 

I uninstalled the prerelease version from pypi and tried out using the git repository instead, I believe from https://github.com/Breakthrough/PySceneDetect/commit/3b28522cb4b9fde0e2374bd73e10d782d3e5f95d
When I was using that on Windows 11 in an anaconda environment, it worked really well. I think it was defaulting to `av` but I might've specified it manually too to be sure. Although something I did notice was for some files, `av` didn't have as much of a performance benefit over `opencv`. I will try again today, maybe using Linux this time around. I think for some files, `opencv` would be faster than `av`, but vice-versa. Does `av` use the `hwaccel` function in `ffmpeg`?

**Comment by camjac251** [comment]
On linux, the backend speed differences seem pretty big. `pyav` is starting at 90fps then drops to 55. `opencv` starts at 380fps and increases to 450 peak.

I also noticed something weird, maybe it's by design. My command currently is `scenedetect -b pyav --input "file.mkv" detect-content list-scenes -o /path/to/pyscenedetect/csv save-images -j --quality 100 -o /path/to/pyscenedetect/thumbs` but it's only maxing out at 95% on the info when running the command for the jpg quality readout.

**Comment by Breakthrough** [comment]
Interesting regarding the performance, I haven't tested it on a large number of videos yet, but I also noticed it provides a less consistent framerate throughout the run.  Now that different backends exist, adding new ones is relatively easy, so I'm curious if there are any other libraries that might have better performance (curious how gstreamer stacks up or if there's a GPU enabled decoder).  I believe you can bring your own ffmpeg binaries with PyAV, so if it doesn't use hardware acceleration it's certainly possible to either build it manually or try to find a precompiled version.

And thanks for pointing that out, that's a bug!  Quality is effectively unchangeable in v0.6-dev3 and 95 for JPEG, 100 for WebP.  Will add a task to get that in for the next beta release (taking some time with that one as hope it can be the final beta).

Thank you so much for taking the time to test the beta and provide feedback, it's been incredibly helpful.

**Comment by Breakthrough** [comment]
Interestingly, I get significantly better decoding performance on Linux with OpenCV versus Windows (nearly twice as fast on Linux).

@camjac251 to answer your question re: hwaccel, it looks like [PyAV does not support it](https://github.com/PyAV-Org/PyAV/blob/main/docs/overview/caveats.rst), so that may explain the difference.  Interestingly, the justification in the library reads:

> There are some features we may elect to not implement because we don't believe they fit the PyAV ethos. The only one that we've encountered so far is hardware decoding. The [FFmpeg man page](https://ffmpeg.org/ffmpeg.html) discusses the drawback of -hwaccel:
>  >    Note that most acceleration methods are intended for playback and will not be faster than software decoding on modern CPUs. Additionally, ffmpeg will usually need to copy the decoded frames from the GPU memory into the system memory, resulting in further performance loss.

I think the most recent version of OpenCV should work with most media types now including multitrack audio files, but there could still be some edge cases where PyAV is required.
