### ISSUE TITLE
ImportError: cannot import name 'VideoManager' from 'scenedetect' 

### ISSUE THREAD

**Issue by LianShuaiLong** [Breakthrough/PySceneDetect#267]
Follow the Quick Start (Python API)
 I  run the scripts in my docker with PySceneDetect version ==v0.6-dev3（installed by pip）
unfortunately, i get this error:

`ImportError: cannot import name 'VideoManager' from 'scenedetect'`

however, it runs well with command  line:

`scenedetect -i video.mp4 detect-content split-video`

**Comment by Breakthrough** [comment]
Hi @LianShuaiLong;

Make sure you are looking at the v0.6 documentation (bottom right should say 'v0.6', not 'latest'):
http://scenedetect.com/projects/Manual/en/v0.6/api.html#quickstart

VideoManager is part of the old API.  Can you share your script?

Thank you!

**Comment by LianShuaiLong** [comment]
> 

This is my simple test script:
`from scenedetect import VideoManager
from scenedetect import SceneManager

#for content-aware scene detection
from scenedetect.detector import ContentDetector

import argparse

def parse_parser():
    parser=argparse.ArgumentParser()
    parser.add_argument('--input_video',type=str,default='video.mp4',help='Video path')
    parser.add_argument('--threshold',type=int,default=30,help='Scene detect threshold')
    args = parser.parse_args()
    return args

def find_scenes(video_path,threshold=30):
    #create our video & scene manager, then add the detector
    video_manager = VideoManager([video_path])
    scene_manager = SceneManager()
    scene_manager.add_detector(ContentDetector(theshold=theshold))

    #improve processing speed by downscaling before processing
    video_manager.set_downscale_factor()

    #start the video manager anf perform the scene detection
    video_manager.start()
    scene_manager.detect_scenes(frame_source=video_manager)

    # each returned scene is a tuple of the (start,end) timecode
    return scene_manager.get_scene_list()


if __name__=='__main__':
    args = parse_parser()
    video_path = args.input_video
    threshold = args.threshold
    scene_list = find_scenes(video_path,threshold)
    print(scene_list)
`

**Comment by Breakthrough** [comment]
In v0.6 you can just use the `detect` function to get a scene list, e.g. instead of

    scene_list = find_scenes(video_path, threshold)

You can write:

    scene_list = scenedetect.detect(video_path, ContentDetector(threshold=threshold))

See [this example](http://scenedetect.com/projects/Manual/en/v0.6/api.html#example) for more advanced use.

Thanks!

**Comment by Breakthrough** [comment]
There is now a backwards compatibility layer in the latest v0.6 release (rc0) which should allow *most* v0.5.x scripts to work with the new version.  This layer is only temporary and will be removed in a future version, so new code should not use VideoManager anymore.
