### ISSUE TITLE
Error generating stats_file

### ISSUE THREAD

**Issue by mohannad57** [Breakthrough/PySceneDetect#28]
Hello,
I'm trying to use the PySceneDetect via CLI and the application generates an error when adding the -s / --statsfile option.
I'm using version v0.4
I even used the same video file available in the PySceneDetect/docs/examples/usage-example.md 

but still same error. 
here is the command I executed 
         scenedetect -i goldeneye.mp4 -o scenes_list.mp4 -d content -si -df 4 -s stats.csv
and here is the result

[PySceneDetect] Detecting scenes (content mode)...
[PySceneDetect] Parsing video goldeneye.mp4...
[PySceneDetect] Video Resolution / Framerate: 1280 x 544 / 23.976 FPS
[PySceneDetect] Subsampling Enabled (4x, Resolution = 320 x 136)
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).
Traceback (most recent call last):
  File "scenedetect\__main__.py", line 40, in <module>
  File "scenedetect\__init__.py", line 302, in main
  File "scenedetect\__init__.py", line 144, in detect_scenes_file
  File "scenedetect\__init__.py", line 228, in detect_scenes
TypeError: can only concatenate list (not "dict_keys") to list
Failed to execute script __main__

Although I don't have much experience with python but I will look into it and try to fix it. 

but I though it is something need to be addressed.

**Comment by mohannad57** [comment]
I found the issue and fixed it on my local version by converting the "stats_file_keys" to list in line 228 or at assignment at line 225. 

but I think this need to be fixed on GitHub

**Comment by Breakthrough** [comment]
v0.5-beta has been released, and v0.5 should be out sometime this month.  Thank you for your submission, and helping to make PySceneDetect even better 👍
