### ISSUE TITLE
Please convert them from tuple to list

### ISSUE THREAD

**Issue by ashishupadhyaa** [Breakthrough/PySceneDetect#281]
https://github.com/Breakthrough/PySceneDetect/blob/295c3c3c1430c5aad2716a5511bfcc4c8c321c81/scenedetect/detectors/content_detector.py#L100

As the above line returns the tuple as a type, it creates an error when running the program. It needs to convert to a type that is mutable.

**Comment by Breakthrough** [comment]
This issue was fixed already in v0.5.6.1:
https://github.com/Breakthrough/PySceneDetect/releases/tag/v0.5.6.1

Please update to a newer version of PySceneDetect, or use an older version of OpenCV as a workaround.  Thanks.
