### ISSUE TITLE
Skip frame for Adaptive

### ISSUE THREAD

**Issue by MattFanto** [Breakthrough/PySceneDetect#283]
**Description of Problem & Solution**
I'm trying to process many high fps videos and unfortunately the video processing would be too low for our use case, I saw the skip frames option. Unfortunately it can't be applied to the Adaptive algorithm due to incompatibility with the mandatory scene stats.
I was wondering if it would be possible to create a more generic implementation of skip frames that can be used with the Adaptive detector.

**Proposed Implementation:**
Eventually adding a parameter to VideoManager, would allow skipping the frames directly there, creating an abstraction for the downstream detector so that the least amount of changes would be required.

**Alternative Solutions:**
The alternative solution in my case would be to reduce the FPS eagerly, with some libraries like FFmpeg. Unfortunately, that would be much more resource-consuming compared to the lazy approach above.

**Comment by Breakthrough** [comment]
I'm pursuing combining AdaptiveDetector's functionality with ContentDetector for the next release, by turning it into an online algorithm.  This would also mean it no longer requires a StatsManager.  It does mean some API changes as the way callbacks work right now, they assume a cut can be detected immediately, but that's something that should be resolved for the long term regardless.

I'll use this as a tracking issue for that feature.  In general have you had to tweak the parameters you're using with Adaptive?  If this proceeds as planned, I want to verify that the defaults are reasonable for most use cases.

**Comment by MattFanto** [comment]
Hi @Breakthrough thanks a million for your reply, great news looking forward to trying the new version.

Regarding your question: at least to me the default are reasonable

**Comment by Breakthrough** [comment]
I managed to make this work in the Python API, here's .WHL if you're interested in testing (can be installed using `pip`):

https://ci.appveyor.com/api/buildjobs/2oolsq1b3ik810ak/artifacts/dist%2Fscenedetect-0.6.1.dev0-py3-none-any.whl

Couple things remain as TODOs, but most of them are for the CLI and code organization - the above build should work just fine as is.

 - [ ] Had to change short option of `-w`/`--frame-window` to `-f`, using it instead for `--weights`
    - consider a different name for `--weights` or if this breaking change should proceed
 - [ ] Decide if this functionality should be merged with ContentDetector or remain separate
     - Arguments for merging: It can be turned off by setting window size to zero, doesn't affect main score calculation, most users already are using ContentDetector/ `detect-content` so will experience improvement when updating
     - Arguments against merging: It will slightly complicate ContentDetector more, may cause changes in behavior for end users
 - [ ] If merge is made, mark AdaptiveDetector/`detect-adaptive` as deprecated, otherwise update examples to use AdaptiveDetector/`detect-adaptive` instead of ContentDetector/`detect-content`

**Comment by MattFanto** [comment]
Hi @Breakthrough , sorry for the late reply I just came back from holiday and thanks a million for the wheel.
I'm testing the code since I was using v0.5 some changes are required to migrate to v0.6.x, in any case the skip frame is working great.
I'm available also to test a release candidate as soon as it is available

**Comment by MattFanto** [comment]
Hi @Breakthrough , all working good I have adapted the params etc.. and I didn't see any regression, the performance improvement in our case is excellent, thanks a lot!
May I ask you when are you going to release it to PyPI? I'm wondering from a deployment perspective if I should commit the wheel or I can just wait for the package in PyPI and install via pip

**Comment by Breakthrough** [comment]
I'm not sure on an exact timeline, but I hope to have a pre-release of v0.6.1 within the next couple weeks on PyPI.  The final v0.6.1 release will probably be near the end of September.  Unfortunately I can't commit to any specific dates yet as I'm busy with IRL stuff the next couple weeks.

**Comment by MattFanto** [comment]
Thanks for the info, no problem at all. In any case I can use the wheel
