### ISSUE TITLE
Focus or ROI area

### ISSUE THREAD

**Issue by rogiedodgie** [Breakthrough/PySceneDetect#286]
It would be great to have this focus on a single region that is known to change between scenes.
For example, if a small image or dot at the lower left flashes on scene changes, and you could focus detection in that area.
Best,
Roger

**Comment by Breakthrough** [comment]
This is being tracked in #147.  Scheduling it seems to have fallen through the cracks, so scheduling this for v0.7 (might consider adding this sooner in v0.6.1/v0.6.2, but just want to make sure it's being tracked).  Thanks!
