### ISSUE TITLE
Video Analysis

### ISSUE THREAD

**Issue by mohannad57** [Breakthrough/PySceneDetect#30]
I'm trying to generate stats_file to try to determine the best threshold (-t).
I was able to generate it using -s FILE_NAME and also generated the splits using -co, but I'm not able to plot the graph like the one in (https://raw.githubusercontent.com/Breakthrough/PySceneDetect/resources/images/threshold-param-example.png).

the stats file contains the following columns and 1979 rows (frames) for the sample video provided in the docs.
Frame Number	Timecode	 delta_hue	delta_lum	  delta_hsv_avg	delta_sat
my question is how can I get a nice graph that helps me determine the right threshold?

**Comment by Breakthrough** [comment]
Hello @mohannad57;

You'll want to plot the `delta_hsv_avg` column against the frame number for a nice smooth graph (or the timecode, if your spreadsheet software supports it).  This is what is compared to the threshold/sensitivity value (`-t`) in `content` mode.

Let me know if this helps!
