### ISSUE TITLE
Support cropping / region of interest

### ISSUE THREAD

**Issue by Breakthrough** [Breakthrough/PySceneDetect#302]
Processing only a sub-set of a video frame should be possible. This can greatly improve performance and detection accuracy in some cases.

To avoid any issues with cropping or output, both `save-images` and `split-video` should still output the full video.  Cropping of the output can be considered in the future, but should be avoided if possible and done by post-processing the output of PySceneDetect. The same applies to non-rectangular ROIs or overlapping regions.

This was originally brought up in #147. This is also a feature in PyVfxShotDetect [1], so we can consider implementing something similar by creating a wrapper for `VideoStream`.

[1] https://github.com/ThomasWeckenmann/PyVfxShotDetect/blob/master/scenedetect/bbox_video_stream.py

**Comment by ankandrew** [comment]
Looking forward this feature 🙏

**Comment by cdgraff** [comment]
+1 will be amazing have this feature! I need too...

**Comment by Breakthrough** [comment]
Can anyone share if they require a GUI for this purpose, or is command line acceptable? cc @ankandrew  @cdgraff

I'm thinking the regions can be a set of polygon masks similar to how DVR-Scan handles this.  Similarily, if we need a GUI, I may repurpose [the region editor from DVR-Scan](http://www.dvr-scan.com/guide/#region-editor) for this purpose, since that has most of the required functionality.  This also means we can support non-rectangular masks.
