### ISSUE TITLE
Generates unreadble .csv files for scene detection

### ISSUE THREAD

**Issue by Sukanya-Kudi** [Breakthrough/PySceneDetect#31]
Using the command "scenedetect -i goldeneye.mp4 -o scenes_list.csv -d content -si -df 4"
generates unreadable .csv files.

**Comment by lejinghu** [comment]
I was wondering about the same thing. There's a typo in the tutorial. It shoud be ”-co" for csv files and "-o" for mkv files.

**Comment by mohannad57** [comment]
See issue  [#29](https://github.com/Breakthrough/PySceneDetect/issues/29) for the same concern and response

**Comment by Sukanya-Kudi** [comment]
There is another issue with the split that is done with the use of mkvmerge --split. The timecodes supplied are not used at all and can be verified from (https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise ).
