### ISSUE TITLE
Limit number of used processors

### ISSUE THREAD

**Issue by yossibiton** [Breakthrough/PySceneDetect#314]
**Description of Problem & Solution**
I have noticed that PySceneDetect utilize all available cores when running (8 cores in my case). Is there a way to limit the number of used cores (so I can run other tasks in parallel) ?

**Comment by Breakthrough** [comment]
What options are you using?  Right now there should only be 2 threads - a decoding thread, and a detection thread.  Also what OS are you on?  Many have ways of limiting what cores a program can execute on.

**Comment by yossibiton** [comment]
I looked at the code, and I see there are only 2 threads but practically all 8 cores are almost fully utilized during run. I suspect OpenCV is the main consumer, since it's the default backend.
My OS is Ubuntu, and this is my relevant code sample : 
```
video = open_video(video_path)
scene_manager = SceneManager()
scene_manager.add_detector(
   AdaptiveDetector(adaptive_threshold=2.0, min_scene_len=40, min_content_val=20, window_width=25))
scene_manager.detect_scenes(video)
scenes_list = scene_manager.get_scene_list()
```

**Comment by Breakthrough** [comment]
You're probably right.  Unfortunately those threads seem to be out of my control, but you might have some luck using `taskset` to pin your workload to only a few CPUs, e.g. https://unix.stackexchange.com/a/23109
