### ISSUE TITLE
error in python example: detect_scenes_file() takes exaclty 2 arguments (3 given)

### ISSUE THREAD

**Issue by applesleam** [Breakthrough/PySceneDetect#32]
Hello! This is an excellent project and thanks for your contribution!
I just try your demo in python:
```python
import scenedetect

scene_list = []        # Scenes will be added to this list in detect_scenes().
path = 'my_video.mp4'  # Path to video file.

# Usually use one detector, but multiple can be used.
detector_list = [
    scenedetect.detectors.ThresholdDetector(threshold = 16, min_percent = 0.9)
]

video_framerate, frames_read = scenedetect.detect_scenes_file(
    path, scene_list, detector_list)

# scene_list now contains the frame numbers of scene boundaries.
print scene_list

# create new list with scene boundaries in milliseconds instead of frame #.
scene_list_msec = [(1000.0 * x) / float(video_fps) for x in scene_list]

# create new list with scene boundaries in timecode strings ("HH:MM:SS.nnn").
scene_list_tc = [scenedetect.timecodes.get_string(x) for x in scene_list_msec]
```
When I run the simple python example, I encountered following problems:
```
TypeError: detect_scenes_file() takes exactly 2 arguments (3 given)
```

And I find no other people have the same problem with me, can anybody help me with this issue? Thanks a lot!

**Comment by robin-garnham** [comment]
Looks like it was changed about four months ago but the docs weren't updated:

https://github.com/Breakthrough/PySceneDetect/commit/a18ea066abf867c27459b258faf300a0a625bfff

Looks like it needs a scene manager object...

I'm going to try from main() in https://github.com/Breakthrough/PySceneDetect/blob/fc8d251b7f36ef1c2381e1276dc2966ad181ea3d/scenedetect/__init__.py

**Comment by robin-garnham** [comment]
Thanks for responding so quickly. It looks like that is compatible with the cli approach. When called within a script though I've been having problems. 

File "//anaconda/lib/python3.5/site-packages/PySceneDetect-0.3.6-py3.5.egg/scenedetect/manager.py", line 55, in __init__
AttributeError: 'dict' object has no attribute 'detection_method

**Comment by Breakthrough** [comment]
@robin-garnham Whoops, my apologies, I glanced right over the `args` argument.  Yes, I'll have to add a page to the documentation about how that dict should be formatted.

**Comment by Cospel** [comment]
Wow this projects is great. I also used version 0.3 so I will wait on updated docs. Thank you!

**Comment by Cospel** [comment]
Ok what i have right now is working solution:
`

      class PySceneDetectArgs(object):
        def __init__(self, input, type='content'):
        self.input = input
        self.detection_method = type
        self.threshold = None
        self.min_percent = 95
        self.min_scene_len = 15
        self.block_size = 8
        self.fade_bias = 0
        self.downscale_factor = 1
        self.frame_skip = 2
        self.save_images = False
        self.start_time = None
        self.end_time = None
        self.duration = None
        self.quiet_mode = True
        self.stats_file = None


      scene_detectors = scenedetect.detectors.get_available()

      smgr_content   = scenedetect.manager.SceneManager(PySceneDetectArgs(input=video_path, type='content'),   scene_detectors)
      #smgr_threshold = scenedetect.manager.SceneManager(PySceneDetectArgs(input=video_path, type='threshold'), scene_detectors)

      scenedetect.detect_scenes_file(path=video_path, scene_manager=smgr_content)
      #scenedetect.detect_scenes_file(path=video_path, scene_manager=smgr_threshold)

      detected_scenes = smgr_content.scene_list
`

**Comment by tamirpassi** [comment]
Hi There,

where can we find a working example of a python program matching the newly intriduced API changed ( v0,4)?

thanks!

**Comment by Breakthrough** [comment]
Hello everyone;

Unfortunately, the v0.4 API isn't completed yet, due to major structural changes to PySceneDetect as a whole, and thus the documentation is not written yet.  However, I do plan on moving to v1.0 once a stable API has been implemented.

In the meantime, you may want to consider using PySceneDetect v0.3.5 if that meets your requirements.  My apologies for having to use a workaround for the time being - I hope to have a stable API implemented by the end of next month, now that the command-line functionality is stable.
