### ISSUE TITLE
Different scene detection for a video and a part of the same video

### ISSUE THREAD

**Issue by tahayass** [Breakthrough/PySceneDetect#327]
**Bug/Issue Description:**
Hey ! I'm confused here. i ran your code on a video thats 5min in length and did a good job at detecting scene cuts. But, with the same exact parameters it detects basically randomly scene cuts for a subset of the same video of 3min or a larger video that contains the original 5min video. I really dont understand why ! 

**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using, for example:

I'm using the python API

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.
I'm using the python API

**Expected Behavior:**
Same scene cuts detected for a video and a subset of the same video
**Computing Environment:**
 - OS: windows 10
 - Python Version: 3.11.3
 - OpenCV Version: 4.7.0

**Additional Information:**
None i can think of

**Comment by Breakthrough** [comment]
Can you provide a code snippet that reproduces the issue you're facing?

**Comment by Breakthrough** [comment]
@tahayass can you provide any additional information to help triage the issues you are facing?

**Comment by Breakthrough** [comment]
Closing due to lack of response.
