### ISSUE TITLE
load-scenes: make faster and clearer

### ISSUE THREAD

**Issue by toomanynights** [Breakthrough/PySceneDetect#347]
Hi!

I've just tried out the new feature, https://github.com/Breakthrough/PySceneDetect/pull/294
I'd like to suggest a couple of things how it could me made a bit better.

**Problem/Use Case**

First thing: way I see it,  primary use case of "load-scenes" is to save time on detection when a single video must be processed several times. There are other use cases, of course, but for this one it doesn't do much good: detection via the list takes nearly as much time as without it. 

Another thing is that currently I can't be certain if the script works with the list at all. At first I made a list without "-s" argument, then I read the document and added the argument, and didn't notice any difference.

**Solutions**

It would be great to make it so having the .csv allows to skip the detection process entirely (if that's even possible of course).
Also would be nice if the script informed that it currently uses the list instead of a detection from scratch.

Thank you for your amazing work!

**Comment by Breakthrough** [comment]
Thanks for the feedback.  We can definitely add some logging to make it more clear when a pre-existing scene list is being used.

Regarding performance, this is the main reason why loading statsfiles was deprecated - with the default settings and downscale factors, processing the video is usually pretty fast.  However, there are certainly a lot of ways `load-scenes` could probably be improved performance-wise, so happy to look more into that for the next release.

Thanks for the feedback!

**Comment by Breakthrough** [comment]
This is now fixed in `develop` and will be included in v0.6.3. The `load-scenes` command now skips detection and produces output much faster.
