### ISSUE TITLE
Comma-separated frame list

### ISSUE THREAD

**Issue by Dendraspis** [Breakthrough/PySceneDetect#349]
**Problem/Use Case**

Depending of the use case, it would be great to get not only the timecode list, but (also) the exact frame numbers as comma-separated list for fast readout and usability. If usable, frame numbers are more accurate or less problem prone than time codes, that has to be translated when you work with frame numbers.

**Solutions**

Add a *Comma-separated frame list* as well. 

**Proposed Implementation:**

```
[..]
[PySceneDetect] Comma-separated timecode list:
  01:00:02.682,01:00:04.392
[PySceneDetect] Comma-separated frame list:
  86378,86419
```

**Alternatives:**

Make the output format optional, e.g. `scenedetect -i video.mp4 list frame`.

**Comment by Breakthrough** [comment]
This is probably better suited as a [config file option](https://www.scenedetect.com/docs/latest/cli/config_file.html), but this is certainly possible.  Something to define the cut list format (timecode, second, frame number, or none).

**Comment by Breakthrough** [comment]
Added a new `cut-format` option under the `[list-scenes]` for this in the config file for the upcoming 0.6.3 release.
