### ISSUE TITLE
`list-scenes` option `-q`/`--quiet` does not suppress all output

### ISSUE THREAD

**Issue by Boulder08** [Breakthrough/PySceneDetect#356]
**Problem/Use Case**

The comma-separated timecodes list that is output distracts the user from important information when PySceneDetect is used inside some other tool. Setting -q does stop the table from showing up but not this list.

**Solutions**

Make -q skip the list display as well, or add a separate parameter for this option. The progress bar is a very useful feature so muting all output is not a good workaround.

**Comment by Breakthrough** [comment]
What version of PySceneDetect are you using?  In the latest version, you shouldn't see any output when using `-q` at all.  Do you see the same issue when you use `-v none`?

I can also look into adding a config file option for always showing the progress bar.  The progress bar always goes to stderr, so it might be okay to enable it regardless of the verbosity.

**Comment by Boulder08** [comment]
It's v0.6.2, installed via pip3.

Sorry, I think I should have been more clear: the issue is in the list-scenes parameter. Setting -q for pyscenedetect itself mutes everything (as does -v none).

**Comment by Breakthrough** [comment]
Gotcha, thanks for clarifying.  Originally this was to allow using `scenedetect` output directly with `mkvmerge` but this ended up getting overlooked with the logging overhaul in v0.6.  It shouldn't be a problem to hide it now, thanks for the report.
