### ISSUE TITLE
Output File Name Change

### ISSUE THREAD

**Issue by SasaniP** [Breakthrough/PySceneDetect#359]
**Problem/Use Case**

I do have trouble accessing the output videos because of their name template.

https://github.com/Breakthrough/PySceneDetect/blob/b54aff9ae6c3a07384bd0673040c54895fb39f20/scenedetect/video_splitter.py#L185
https://github.com/Breakthrough/PySceneDetect/blob/b54aff9ae6c3a07384bd0673040c54895fb39f20/scenedetect/video_splitter.py#L270

**Solutions**

I would rather save the files as 0.avi , 1.avi , 2.avi etc.

**Proposed Implementation:**
https://github.dev/Breakthrough/PySceneDetect/blob/b54aff9ae6c3a07384bd0673040c54895fb39f20/scenedetect/video_splitter.py#L185-L186
185    output_file_template: str = '$SCENE_NUMBER.mp4',
https://github.dev/Breakthrough/PySceneDetect/blob/b54aff9ae6c3a07384bd0673040c54895fb39f20/scenedetect/video_splitter.py#L269-L270
270                    VIDEO_NAME=video_name, SCENE_NUMBER=(i + 1))

**Alternatives:**

Have the default option to save the files in the existing way. And if the user needed to save files in a less complicated way, this function change.

**Comment by Breakthrough** [comment]
This should be possible.  However I think a more extensible approach for this might be to instead use a callback, that itself can be called to format the name of each scene.  The input would be all the info you need to generate the filename (or maybe a dataclass with it).

**Comment by Breakthrough** [comment]
This will be fixed in v0.6.3, added a new formatter argument to allow customizing string output.
