### ISSUE TITLE
Extraction half of frames

### ISSUE THREAD

**Issue by vladoossss** [Breakthrough/PySceneDetect#360]
When I try to extract keyframes from a long video(about 30 min and more), it only works for half the length of the video and then stops:
![image](https://github.com/Breakthrough/PySceneDetect/assets/71467601/6fc42cd4-9d2d-4ad9-aade-da820447ac08)

I will be appreciate your help!

**Comment by Breakthrough** [comment]
Could you provide debug logs to assist?  You can add `-v debug -l BUG_REPORT.txt` to create one.  Thanks.

**Comment by vladoossss** [comment]
> Could you provide debug logs to assist? You can add `-v debug -l BUG_REPORT.txt` to create one. Thanks.

I started with debug, but it's still not clear for me to understand what happend:
![image](https://github.com/Breakthrough/PySceneDetect/assets/71467601/619c78b0-a792-45a2-a316-40cb0e6c6ad4)

But i figured out that my test video has ~50fps. Can the problem depends on huge fps?

**Comment by Breakthrough** [comment]
Is that the same video?  If the framerate is 50 FPS, then 131833 frames represents 43 minutes [1] that PySceneDetect processed.  The progress bar bases the total # of frames on whatever the video container reports, which may not be accurate.  To confirm this, you can try re-encoding the video with ffmpeg and then process it again with PySceneDetect.

Are you seeing this problem on different videos or just a single input?  Have you tried another backend (e.g. `--backend pyav`)?

[1]  131833 frames / (50 frames/sec * 60 secs/min) = 43 minutes

**Comment by vladoossss** [comment]
> Is that the same video? If the framerate is 50 FPS, then 131833 frames represents 43 minutes [1] that PySceneDetect processed. The progress bar bases the total # of frames on whatever the video container reports, which may not be accurate. To confirm this, you can try re-encoding the video with ffmpeg and then process it again with PySceneDetect.
> 
> Are you seeing this problem on different videos or just a single input? Have you tried another backend (e.g. `--backend pyav`)?
> 
> [1] 131833 frames / (50 frames/sec * 60 secs/min) = 43 minutes
> 
> Edit: To answer your question, the problem shouldn't depend on framerate as long as it is fixed.

I've tried 2 diffrent video(both 50 fps, ~1.5 hours). But it's always processes half of the frames. 

I agree with your calculation. But when i save one image per scene and looking at last image, i see ~the middle frame of my vildeo.

I also used another backend(moviepy) and it works well(with all frames), but too slow compared to opencv(4-5 times slower).

**Comment by Breakthrough** [comment]
Are you able to share a sample video with me that shows the issue?  That would be useful to help debug what the issue may be.  Thanks!
