### ISSUE TITLE
url input ,1080p video much slower 

### ISSUE THREAD

**Issue by babyta** [Breakthrough/PySceneDetect#381]
as title,when test,i found that problem。Looking forward to your reply

**Comment by Breakthrough** [comment]
I'm not sure this is enough information to go by, could you please provide:

**Description:**

Describe what the bug or issue is (e.g. crashes when setting X) and how it can be reproduced.

**Command:**

Place a full copy of the command line options you are using here, for example:

`scenedetect -i some_video.mp4 -s some_video.stats.csv -o outdir detect-content --threshold 28 list-scenes save-images`

**Output:**

Copy the output of running the application here. Where possible, generate a debug log by adding `-v debug -l BUG_REPORT.txt` to the beginning of your command, and **attach `BUG_REPORT.txt` to your issue**.

**Environment:**

The operating system and how you installed PySceneDetect may be relevant to the issue. Please run `scenedetect version --all` and copy the output here, or provide other details on how PySceneDetect was installed.

**Media/Files:**

Attach or link to any files relevant to the issue, including videos (or YouTube links), scene files, stats files, and log output.

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by babyta** [comment]
https://drive.google.com/file/d/1h5tztZkpV6ziJzgtVieJqcnhF4Bo82f_/view?usp=sharing
=================This is the url
![image](https://github.com/Breakthrough/PySceneDetect/assets/37787795/4009c850-4ccb-49b2-b464-f6ac10033a06)
=================This is a speed comparison. The URL input is very slow, but the same video is downloaded locally as input and the strips are split very quickly.


from scenedetect import open_video, SceneManager, split_video_ffmpeg
from scenedetect.detectors import ContentDetector
from scenedetect.video_splitter import split_video_ffmpeg

video_path = '1080pvdieo.mp4'
threshold=27.0
# Open our video, create a scene manager, and add a detector.
video = open_video(video_path)
scene_manager = SceneManager()
scene_manager.add_detector(
    ContentDetector(threshold=threshold))
scene_manager.detect_scenes(video, show_progress=True)
scene_list = scene_manager.get_scene_list()

================= this is code

**Comment by Breakthrough** [comment]
URL input is handled by OpenCV if you don't change anything, have you tried using a different backend?  https://www.scenedetect.com/docs/0.6.2/api/backends.html

**Comment by babyta** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test.py", line 9, in <module>
    video = open_video(video_path, backend='pyav')
  File "D:\ProgramData\miniconda3\envs\py39pt1121\lib\site-packages\scenedetect\__init__.py", line 143, in open_video
    return backend_type(path, framerate, **kwargs)
  File "D:\ProgramData\miniconda3\envs\py39pt1121\lib\site-packages\scenedetect\backends\pyav.py", line 107, in __init__
    self._io = open(path_or_io, 'rb')
OSError: [Errno 22] Invalid argument

**Comment by babyta** [comment]
When I use pyav as backends, I get an error directly.

**Comment by babyta** [comment]
cv2.VideoCapture   When reading a URL, if the video resolution corresponding to the URL is very high and the data rate is very high, it will be very slow.

**Comment by Breakthrough** [comment]
Thank you for following up on this, I appreciate it.  If you suspect this is due to OpenCV and isn't just an issue with using `ffmpeg` (or which ever backend OpenCV itself is using to process the stream), you might want to [reach out in their repo](https://github.com/opencv/opencv/issues).

Best regards!
