### ISSUE TITLE
Use csv as input for scene splitting

### ISSUE THREAD

**Issue by macguruza** [Breakthrough/PySceneDetect#383]
When running scenedetect to generate the stats file and split the video into scenes according to the generated csv file, we often get false positives for the split points no matter what detection method we use. It would be extremely useful to be able to edit the csv file to reflect the split points that are wanted and then use that csv file as input to scenedetect to split the input file according to those edited time stamps.

**Comment by Breakthrough** [comment]
This was added as [the `load-scenes` command](https://www.scenedetect.com/docs/latest/cli.html#load-scenes).
