### ISSUE TITLE
No output to list-scenes

### ISSUE THREAD

**Issue by macguruza** [Breakthrough/PySceneDetect#384]
list-scenes and load-scenes are fantastic. I noticed while playing with list-scenes that the --quiet global option suppresses output of  the scene list CSV file, whereas --verbosity none does not. Minor issue but spent some time figuring out what was happening.

**Comment by Breakthrough** [comment]
Are you not seeing any output files get created when you use -q/--quiet?  I tried to reproduce this just now but am unable to, things seem to be working okay on my end.

Could you provide the full command line arguments and the version of PySceneDetect you are using?

**Comment by macguruza** [comment]
I struggled to reproduce it now myself. Then I found an older csv file in
my home directory. I suspect that, when no --output directory was
specified, my macOS home directory (~) was used instead of the current
directory (.). Possibly an environment variable but not sure.

**Comment by Breakthrough** [comment]
Closing as not reproducible for now, but feel free to re-open if you encounter the issue again or file a new issue.  Thank you!
