### ISSUE TITLE
QP file output

### ISSUE THREAD

**Issue by tormento** [Breakthrough/PySceneDetect#388]
x265 (and other software) accepts a .qp file to force a frame type to be applied to a certain frame.

An example is:
```
0 I -1
1640 I -1
3789 I -1
17191 I -1
31784 I -1
33927 I -1
```
to have proper scene change cuts.

[Here](https://x265.readthedocs.io/en/master/cli.html?highlight=qpfile#cmdoption-qpfile) you can find the syntax.

It can be derived by chapters but it's almost of no use when wanting a clean cut frame per each scene.

Would you mind to add that kind of output?

**Comment by Breakthrough** [comment]
Thanks, this falls under some of the other open issues to expand on output formats.  I think we should add a new command like `export-scenes` that is dedicated for this purpose, so that the cuts can be saved in various formats.  Updated #344 to include a link to this issue.

I would imagine the command to look something like `export-scenes -o "cuts.qp"` and have the format auto-detected from extension where possible, or explicitly specified with another flag.  We could also allow specifying `export-scenes` several times to generate the output in different formats.

**Comment by tormento** [comment]
Thanks, do you have any ETA?

**Comment by Breakthrough** [comment]
Unfortunately no ETA at this time, but in v0.6.3 there are some features that make workarounds for this a bit easier.  You can change [the format cuts are generated with](https://github.com/Breakthrough/PySceneDetect/blob/releases/0.6.3/scenedetect.cfg#L230) in a config file, and then convert the resulting CSV file or command line output to the QP file.

If in your config file you use:

    [list-scenes]
    cut-format = frames
    
And then use the list-scenes command to generate a CSV file, the first row will be the frames that you need to add `I` frames for.  If you're using the Python API, the `detect` function should already return the info you need.

**Comment by tormento** [comment]
Tried your release, sorry for the delay.

It works ok but the generated CSV is not properly "standard".

I mean: looking at the file, we have a first part with Timecode list and a second part with Scene Number, that are CSV formatted in a really different way each other.

Please, write two files so that I can directly import the Scene number and frame in Excel.

When you will have time (ifyou want to ease my CSV file "postprocessing" :) ), simply output a file with a column of plain scene start frames, almost such as the example I did in the first post.

**Comment by Breakthrough** [comment]
@tormento if you [use the `--skip-cuts` option](https://www.scenedetect.com/docs/latest/cli.html#cmdoption-scenedetect-list-scenes-s) the file will omit the first row to allow it to be imported directly into Excel.

**Comment by Breakthrough** [comment]
@tormento one thing I'm not totally clear on is how this works with input seeking.  Do the frame numbers refer to the encoded output frame numbers, or the frame numbers of the input?

For example, if we use start seeking, does the QP need to still start from frame 0, or should it be shifted?

**Comment by tormento** [comment]
The QP file tells the encoder (x264/x265) where to force a specific type of frame.

In our case, to have a clean scene cut, we need I type, i.e. what once was called a keyframe.

The CSV that PySceneDetect is shifted by 1, compared to encoder convention (wheree first frame is 0), so you need to take the (Start Frame-1) to have the appropriate position.

**Comment by Breakthrough** [comment]
@tormento Thanks, I should have that working now as a new `save-qp` command. Would you like to test a development version to verify?   You can grab one [for Windows here](https://github.com/Breakthrough/PySceneDetect/actions/runs/11116049220/artifacts/1998266531) or from the latest build on PR #427.

Invoking it as `scenedetect -i video.mp4 save-qp` results in the following example `video.qp`:

```
0 I -1
90 I -1
210 I -1
```

Let me know what you think :)

**Comment by tormento** [comment]
Will try ASAP.
