### ISSUE TITLE
The speed at which different backends run.

### ISSUE THREAD

**Issue by lsl0901** [Breakthrough/PySceneDetect#406]
When backend='pyav', it runs much slower than opencv, do you have any ideas？

**Comment by Breakthrough** [comment]
Could you share the performance you get with one vs the other, and also provide the output of `scenedetect version`?

You can also try setting the `threading-mode` param in a config file:
https://github.com/Breakthrough/PySceneDetect/blob/main/scenedetect.cfg#L299

**Comment by lsl0901** [comment]
> 您能否与一个与另一个分享您获得的性能，并提供 ？`scenedetect version`
> 
> 您也可以尝试在配置文件中设置参数：https://github.com/Breakthrough/PySceneDetect/blob/main/scenedetect.cfg#L299`threading-mode`

It really works, thank you！
