### ISSUE TITLE
Get the progress in real time for scene_manager.detect_scenes

### ISSUE THREAD

**Issue by yumianhuli1** [Breakthrough/PySceneDetect#413]
Hello！
  scene_manager.detect_scenes(video, show_progress=True), this function just gets the progress from the command line, is there an api to get the progress in real time? thanks！

**Comment by Breakthrough** [comment]
Right now there isn't a way to get the progress from a different thread, but I'm open to adding this as a feature.  If you can modify the source code you can add a hook somewhere below in that function:

https://github.com/Breakthrough/PySceneDetect/blob/main/scenedetect/scene_manager.py#L882-L894

**Comment by yumianhuli1** [comment]
> This is a good idea. Right now there isn't a way to get the progress from a different thread. If you can modify the source code you can add a hook somewhere below in that function:
> 
> https://github.com/Breakthrough/PySceneDetect/blob/main/scenedetect/scene_manager.py#L882-L894
> 
> If `detect_scenes` took a set of callbacks to invoke on each frame, it could allow for a plugin-type approach for this:
> 
> ```python
> import numpy
> import scenedetect
> 
> class Status:
>     start:scenedetect. FrameTimecode
>     end: scenedetect.FrameTimecode
>     current: scenedetect.FrameTimecode
>     progress: float
>     
> 
> class Metadata:
>     timecode: scenedetect.FrameTimecode
>     events: scenedetect.DetectorEvents
>     stats: scenedetect.DetectorStats
> 
> class Handler:
> 
>     def on_frame(status: Status, frame_bgr: numpy.ndarray, metadata: Metadata) -> ty.Optional[Event]:
>         # ...
> 
>     def on_event(status: Status, frame_bgr: numpy.ndarray, metadata: Metadata):
>         # ...
> ```
> 
> Where metadata would be a dict containing various things such as:
> 
> ```python
> class DetectorEvent:
>     class Type:
>         CUT = 0
>         FADE_IN_START = 1
>         FADE_IN_END = 2
>         FADE_OUT_START = 3
>         FADE_OUT_END = 4
>         MOTION_START
>         MOTION_END 
> 
> 
> class DetectorStats:
>     # Stats should be a dict keyed by a "hash" of the detector params with detector-specific stats.
> ```
> 
> The stats might be something like `{ "delta_hsv": 0.892 }`,

got it，thanks！
