### ISSUE TITLE
Import scenedetect package will have pop-up window

### ISSUE THREAD

**Issue by yumianhuli1** [Breakthrough/PySceneDetect#414]
Hello!
Release Package with Pyinstaller, import scenedetect package will have pop-up cmd window, What code might cause pop-ups？thanks!
Dependency:
from scenedetect import open_video, SceneManager
from scenedetect.detectors import ContentDetector

**Comment by Breakthrough** [comment]
Could you provide a bit more context?  There shouldn't be any popups at all emitted by PySceneDetect directly.

**Comment by yumianhuli1** [comment]
> Could you provide a bit more context? There shouldn't be any popups at all emitted by PySceneDetect directly.

Hello, I have solved it, I except the relevant subprocess code.
