### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by drodz11** [Breakthrough/PySceneDetect#42]
Hello,

I'm running a Mac OSX 10.10.5 with all dependencies installed but I am running into an error when trying to install PySceneDetect.

I download and extract the files, place them on my desktop, but when I run the command
`python setup.py install` with the correct file path I keep receiving the same error message: `IOError: [Errno 2] No such file or directory: 'package-info.rst'`

The .rst file is in same folder, so I am not sure why it isn't being detected. Any help appreciated!

**Comment by xufuou** [comment]
hi @drodz11 I haven't installed from source but this package is listed in [PyPI](https://pypi.python.org/pypi/PySceneDetect/0.3.4). So you can simply run `pip install pyscenedetect`

**Comment by drodz11** [comment]
@xufuou thanks very much! Seems to have done the trick.
