### ISSUE TITLE
When executing the command, the following error occurs and no split video is generated.

### ISSUE THREAD

**Issue by kenvlezhangmin** [Breakthrough/PySceneDetect#425]
**Description:**

When executing the command, the following error occurs and no split video is generated.

Unrecognised option ‘preset’.
Error splitting the argument list: Option not found

**Command:**

scenedetect -i video.mp4 split-video

**Output:**

[BUG_REPORT.txt](https://github.com/user-attachments/files/17142515/BUG_REPORT.txt)

**Environment:**

[PySceneDetect] PySceneDetect 0.6.4
Usage: scenedetect version [OPTIONS]

**Media/Files:**

![image](https://github.com/user-attachments/assets/814d3887-b9a1-41b7-b510-cb0b3e3f849c)
![image](https://github.com/user-attachments/assets/ec547654-60a8-4a60-b9b8-8409a06db7e8)

**Comment by jingsenzhu** [comment]
I also met this problem. How did you solve this?

**Comment by Breakthrough** [comment]
Try updating to a newer version of `ffmpeg` or modifying the arguments passed to it if you cannot upgrade.

What version of ffmpeg are you using?  Could you provide output with the `-v debug` flag added to the beginning of your PySceneDetect command?
