### ISSUE TITLE
bitrate limit with -hq

### ISSUE THREAD

**Issue by whatforiam** [Breakthrough/PySceneDetect#435]
Hello, I have a question. Is there a way to leave the -hq argument, but slightly reduce the bitrate for it? It's just that at moments where there is almost no movement, the bitrate is about 4-7 thousand. I would like to somehow limit it for low-activity scenes, but do not touch it for active ones, it suits me. Well, or at least reduce it a little for all the scenes

**Comment by wjs018** [comment]
There are two ways I can see to go about this. First is that you could manually specify a maximum bitrate. Alternatively, you change the target crf (constant rate factor) that you tell ffmpeg to target when you encode. From your description, it sounds like you want to keep the ability of the encoder to go to high bitrate when needed, but try to reduce the overall bitrate if possible. So, with that in mind, I would recommend adjusting your crf.

I should mention up top that diving into video encoder tuning is a deep, deep well. For a primer, ffmpeg itself has an [h264 encoding guide](https://trac.ffmpeg.org/wiki/Encode/H.264) that covers the basics. Everything I am writing is about h264. I don't really have any experience with h265, but that isn't used by default by PySceneDetect.

### The `-hq` flag

[From the documentation](https://www.scenedetect.com/docs/latest/cli.html#cmdoption-scenedetect-split-video-hq), the `-hq` flag passes `--rate-factor=17 --preset=slow` to ffmpeg. So, by specifying `-hq`, we are simply changing the crf to 17 (lower numbers mean higher quality) and using the `slow` preset in ffmpeg. You can compare this to the defaults used by PySceneDetect below:

| mode | without `-hq` | with `-hq` |
| --- | :-: | :-: |
| crf | 22 | 17 |
| preset | slow | veryfast |

## The `-a` flag

If you want to tune your target crf outside of the options above, then you will need to manually specify the arguments you pass to the ffmpeg encoder. As you can see, the default is a crf of 22 while hq has a crf of 17. So, you will want to choose a value between those two numbers. Also, choosing a slower preset can help with compression at the cost of taking a lot longer to encode. So, an example might be specifying a crf of 20 with a slow preset.

To specify the custom ffmpeg arguments, let's take the default arguments and simply modify them to our needs. The documentation lists the default parameters as 

- Default ffmpeg parameters:
  - `-map 0:v:0 -map 0:a? -map 0:s? -c:v libx264 -preset veryfast -crf 22 -c:a aac`
- Setting crf to 20 and using a slow preset:
  - `-map 0:v:0 -map 0:a? -map 0:s? -c:v libx264 -preset slow -crf 20 -c:a aac`

## Capping the bitrate

If you wanted to manually specify a maximum bitrate for the video, you would use the `-maxrate` and `-bufsize` ffmpeg arguments. So, let's say that you wanted to place a hard cap of 4000 kbps on the example listed above, then you would modify it like this:

- Default ffmpeg parameters:
  - `-map 0:v:0 -map 0:a? -map 0:s? -c:v libx264 -preset veryfast -crf 22 -c:a aac`
- Setting crf to 20 and using a slow preset:
  - `-map 0:v:0 -map 0:a? -map 0:s? -c:v libx264 -preset slow -crf 20 -c:a aac`
- Additionally capping bitrate at 4000 kbps:
  - `-map 0:v:0 -map 0:a? -map 0:s? -c:v libx264 -preset slow -crf 20 -maxrate 4000k -bufsize 4000k -c:a aac`

---

What the proper crf should be is entirely subjective and depends a lot on the type of content that is being encoded. Usually, content that is largely static or has large, uniform areas of color can get away with a higher crf (news content, animation, etc.). Content that involves more motion, rapid changes, or fine details would demand a lower crf (sports, action, etc.). I am *far* from an expert on this topic and, if you search around, there is a lot of advice and opinions on the internet about this topic. Hopefully I have armed you with the keywords you need to track down more reading that is relevant to your type of content.

**Comment by whatforiam** [comment]
thx very much
