### ISSUE TITLE
Report needed crop / aspect ratio

### ISSUE THREAD

**Issue by tormento** [Breakthrough/PySceneDetect#439]
Sometimes a video can change it's aspect ratio without changing resolution, i.e. IMAX sequances or 4:3 old videos in a modern documentary.

Sometimes those clips have to be processed in a different way.

Could you please add some kind of output of real resolution (i.e. removing black bars) and aspect ratio?

**Comment by Breakthrough** [comment]
What are the ffmpeg command line args required to fix this?  Can this be done by updating the defaults?

**Comment by tormento** [comment]
[Here](https://www.ffmpeg.org/general.html#:~:text=FFmpeg%20can%20read%20AviSynth%20scripts,the%20headers%20provided%20by%20AviSynth%2B.) you can find ffmpeg instructions.

I don't know if the latest builds need or not AVS+ installed.

If they need, I suggest you to install the last AVS+ [stable ](https://github.com/AviSynth/AviSynthPlus/releases).

**Comment by tormento** [comment]
Just noticed that I replied to something I had in my head only. :)

I was thinking more at OpenCV than to ffmpeg.

Anyway I have found [this](https://stackoverflow.com/questions/17265381/ffmpeg-get-value-from-cropdetect).

**Comment by Breakthrough** [comment]
Thanks, it seems that link should solve this use case.  Using `ffmpeg` with `cropdetect` on the input first to determine crop factor is a good way to go.
