### ISSUE TITLE
`save_images` API function does not work correctly with some characters

### ISSUE THREAD

**Issue by pengyouak** [Breakthrough/PySceneDetect#450]
**Description:**

If the output dir contains Chinese, the image cannot be saved properly

**Comment by Breakthrough** [comment]
Can you provide a sample stack trace of what you get?

**Comment by pengyouak** [comment]
I have tested the PySenceDetect function locally and it can print the path normally. The problem may occur with cv2.iwrite. There is no error output when calling save_images.

**Comment by Breakthrough** [comment]
I suspected so, I audited the code paths, and PySceneDetect tries to be good about respecting UTF-8 characters in paths.  We can probably work around this issue by writing to an in-memory buffer and then saving that to disk separate.

**Comment by Breakthrough** [comment]
I should have a fix for this in the next version.  During the process I was also able to make it multithreaded so now the `save-images` command should run close to 40% faster in some cases.

**Comment by pengyouak** [comment]
非常感谢你能修复这个问题，这能让我减少很多不必要的麻烦~
