### ISSUE TITLE
why the video must be mkv?

### ISSUE THREAD

**Issue by oneTaken** [Breakthrough/PySceneDetect#46]
The dependency `mkvmerge` is a pain way to install.

**Comment by Breakthrough** [comment]
It's either that or ffmpeg, and mkv seems to provide much more precise timecodes than a pure MP4 container provided by ffmpeg (without reencoding).  For reencoding the source material, ffmpeg is definitely the way to go, although that is one of the things this project aims to avoid.

**Comment by Breakthrough** [comment]
Also note that there will be some development focus on ffmpeg integration after the release of v0.5.  If you have any other suggestions, however, please feel free to bring them up here any time.

Lastly, as noted, the dependency on mkvmerge is optional, and work will be done in the future to allow at least one alternative.
