### ISSUE TITLE
There is no backpressure control which will lead to memory problems

### ISSUE THREAD

**Issue by tangye1234** [Breakthrough/PySceneDetect#467]
Cut detection and video decoding are executed in separate threads and are linked via a FIFO (First In, First Out) queue.
It's common knowledge among queue designers that wherever there's a queue, there lurks a memory trap.
When the decoding process is quicker than the detection process, that is to say, when messages enter the queue at a faster rate than they leave it, the queue will end up with a large number of messages. These messages will require a significant amount of memory to store, which can then result in out-of-memory problems.

**Solutions**

Consequently, we need to set a watermark for the queue to cap the memory usage. Hence, before we decode a video and send a frame to the callback function, we must check the length of the queue. If the queue is on the verge of exceeding the watermark, we should halt the decoding until the queue length drops below the watermark. This way, we can keep the memory consumption under control. Otherwise, it's bound to run out of memory.

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a queue size limit to prevent memory issues in the decode thread. Implemented a watermark check before adding new frames to the queue, and added a wait mechanism when the queue is full.

You can review changes in this commit: https://github.com/kkpo4553/Breakthrough-PySceneDetect-467/commit/9ac06c86f860cd9d8c2bc42f78165fbf0f24e111.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Breakthrough** [comment]
This is an erroneus and false report. The queue is already constructed with a bounded maximum size.
