### ISSUE TITLE
problem while using multi-threading in python

### ISSUE THREAD

**Issue by LynnXie00** [Breakthrough/PySceneDetect#47]
>   File "C:\Users\Lynn\.thonny\BundledPython36\lib\site-packages\scenedetect\detectors.py", line 262, in process_frame
>     if self.last_frame is not None:
> AttributeError: 'ContentDetector' object has no attribute 'last_frame' 

the error above happened when I used muti-thread in python

**Comment by Breakthrough** [comment]
Closing issue until more information is available.
