### ISSUE TITLE
Add support for minimum threshold

### ISSUE THREAD

**Issue by adius** [Breakthrough/PySceneDetect#49]
In `content` mode at the moment it cuts when a certain threshold is exceeded.
So it's a maximum threshold for a scene. 

I need exactly the opposite.
So it's supposed to cut when the change over several frames is pretty low.
=> Minimum threshold for a scene (for a section with a lot of movement).

Use cases: 
E.g. a stationary camera in a car race.
Every round when the cars drive trough the section is a scene.

What do you think?

**Comment by Breakthrough** [comment]
This is a good idea @adius, will have to come up with some sort of CLI flag to toggle between what the threshold means for the content detector.  Right now my efforts are going into reworking the Python API for v0.5 (#57), but this is definitely on my radar going forwards.

That being said, have you seen my other project [DVR-Scan](https://github.com/Breakthrough/DVR-Scan/)?  It seems well suited to what you need, it uses background subtraction to figure out when there is no movement in a scene, and only exports the sections in videos where there is motion.  It's meant more for slow and medium velocity targets, but should work fine for high-speed as well (if you give it a try, please let me know what you think).

The one issue with using the content detector for this (as opposed to DVR-Scan's background subtraction) is that it would not work for slow moving targets, as the inter-frame delta will be much lower versus for fast moving ones.  Also, there are some cases where the distinction between moving objects may become less apparent using the content detection versus background subtraction (e.g. several cars with the same colour that pass the same point at a high speed), as it scores the whole frame versus only the foreground.

That being said, there definitely are some use cases where your idea would greatly benefit the accuracy of the scene detection results.  After the release of PySceneDetect v0.5 (sometime by the end of the month), this will be the first new thing I tackle.

One big issue I need to solve before implementing this is the large amount of CLI arguments PySceneDetect requires, which is becoming unmaintainable when certain flags only apply to certain other flags. I need to come up with a way to divide them into sub-commands to support the addition of more features such as this one.

**Comment by Breakthrough** [comment]
Closing as won't-fix since this functionality can likely be done using DVR-Scan on a specific region of interest.  That being said, if anyone can provide some sample videos where this functionality might be useful or solve any usability issues, please do post it here and this can be revisited.  Thank you.
