### ISSUE TITLE
Feature request: save images as PNG or TIF files

### ISSUE THREAD

**Issue by agricolan** [Breakthrough/PySceneDetect#51]
This would be helpful in enabling text to be extracted from the images.  Thanks.

**Comment by Breakthrough** [comment]
PySceneDetect v0.5-beta allows support for saving images as PNG files via the `save-images --png/-p` command, e.g.:

    scenedetect --input some_video.mp4 detect-content save-images --png --compression 9

You can grab a copy of v0.5-beta from the Releases page if you would like to try the new version or provide some feedback.  The official release of PySceneDetect v0.5 should be out sometime later this month.

Thank you for your submission, and for helping make PySceneDetect even better 👍

**Comment by agricolan** [comment]
Hi Brandon

 

Many thanks for including saving PNG files in the new release.

 

The only problem with the new release v5 beta 1 is that  I get ‘frame_skip must be 0 when using a StatsManager ‘  with -fs 5.  I’m using detect-content and –d 4.   I can’t send a log file as I get a permissions error which I can’t resolve!   I’m using the beta release on Win !0 with Python 3.6 installed.   Is there a work-around to disable the StatsManager as I don’t need to use it and thus avoid getting the error message?

 

Thanks

 

Michael

**Comment by Breakthrough** [comment]
Hi @agricolan;

Sorry about that, and thank you for helping test the beta version.

You can try setting line 97 in scenedetect/cli/context.py to:
        self.stats_manager = None

And see if that solves the issue (haven't tested this yet, but it should resolve the issue). I will try to push a fix for this sometime this weekend and update the beta release (will keep you posted).

Thank you for the bug report, much appreciated!

**Comment by Breakthrough** [comment]
Version 0.5 has now been released!  You can grab it off of `pip` (Windows installer coming soon).  All issues described in this thread have been fixed; closing issue.
