### ISSUE TITLE
found 0 scenes in video

### ISSUE THREAD

**Issue by 2236262519** [Breakthrough/PySceneDetect#59]
scenedetect -i Video/218.mp4 -o Videos/218result.mkv
PySceneDetect] Detecting scenes (threshold mode)... 
[PySceneDetect] Parsing video 218.MP4... 
[PySceneDetect] Video Resolution / Framerate: 480 x 320 / 25.000 FPS 
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required). [PySceneDetect] Processing complete, found 0 scenes in video. 
[PySceneDetect] Processed 500 /500 frames in 0.3 secs (avg. 1688.9 FPS).

I am wondeing why found 0 scenes...
From my perspective, I have seen at least 3 scenes.
Is there anything wrong the way I use it?
ubuntu16.04 , Python 3.5.2
Thanks!

**Comment by Breakthrough** [comment]
Try -d content.
