### ISSUE TITLE
Typo in comments of 0.5-dev

### ISSUE THREAD

**Issue by baicaigithub** [Breakthrough/PySceneDetect#68]
I find the commands in 0.5-dev uses hyphen to join words. However [here](https://github.com/Breakthrough/PySceneDetect/blob/040287dd4fc5d8b095b656f80abe65bf00626f4e/scenedetect/cli/__init__.py#L67) uses underscore. 
E.g. detect_content is used instead of detect-content.

**Comment by Breakthrough** [comment]
Good catch, thank you.
