### ISSUE TITLE
ImportError: module 'scenedetect' has no attribute 'main'

### ISSUE THREAD

**Issue by ishandutta2007** [Breakthrough/PySceneDetect#70]
Operating System is ishandutta2007@MacBook-Pro:~/Downloads/PySceneDetect-0.5-beta$ `python setup.py install`

Finished without any issue.

ishandutta2007@MacBook-Pro:~/Downloads/PySceneDetect-0.5-beta$ `scenedetect --version`

> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in resolve
>     return functools.reduce(getattr, self.attrs, module)
> AttributeError: module 'scenedetect' has no attribute 'main'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/bin/scenedetect", line 11, in <module>
>     load_entry_point('PySceneDetect==0.4.1', 'console_scripts', 'scenedetect')()
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
>     return ep.load()
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
>     return self.resolve()
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2334, in resolve
>     raise ImportError(str(exc))
> ImportError: module 'scenedetect' has no attribute 'main'
> 

ishandutta2007@MacBook-Pro:~/Downloads/PySceneDetect-0.5-beta$ `sw_vers`

> ProductName:	Mac OS X
> ProductVersion:	10.13.6
> BuildVersion:	17G65
>

**Comment by Breakthrough** [comment]
Hi @ishandutta2007;

Thanks for the submission, my apologies for this, there was an error in the setup.py file and some dependencies were missing in the scenedetect module.  I've just updated and re-released v0.5-beta-1 with the fix, you can download it again from here (there's a note at the bottom indicating the fix):
https://github.com/Breakthrough/PySceneDetect/releases/tag/v0.5-beta-1

Running `setup.py intall` again should resolve the issue. If you could provide confirmation that everything works smoothly after re-downloading, that would be much appreciated.  Sorry about that, and thank you again for pointing this out.
