### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#73]
**Bug/Issue Description:**
G:\PySceneDetect-0.5>scenedetect -i "G:\I2\I.mp4" detect-content list-scenes split-video --copy
Traceback (most recent call last):
  File "G:\PySceneDetect-0.5\scenedetect.py", line 34, in <module>
    from scenedetect.__main__ import main
  File "G:\PySceneDetect-0.5\scenedetect\__init__.py", line 52, in <module>
    from scenedetect.scene_manager import SceneManager
  File "G:\PySceneDetect-0.5\scenedetect\scene_manager.py", line 55, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
G:\PySceneDetect-0.5>

**Computing Environment:**
 - OS: Windows 10 Pro
 - Python Version: 3.7.0 32bit
 - OpenCV Version: Don't know, don't install this.

**Additional Information:**
I downloaded source code zip file, after extracting I run setup file. I don't install opencv cause I don't have any issue with previous issue as I did same way.

**Media [Videos/Images/Screenshots]:**
MP4 file

Remove this section if there is no media associated with the issue/bug report.

**Comment by Breakthrough** [comment]
Hi @raj6996;

You can download the cv2 module from:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv

And install it via `pip` (e.g. `pip install [file]`).  Also note that you can install PySceneDetect via `pip` now (e.g. `pip install scenedetect`).

**Comment by raj6996** [comment]
After installing with "pip install opencv-python" command, I got this:

> Error: Invalid value for split-video: mkvmerge is required for split-video -c/--copy.
> Install the above tool to enable video splitting support.

Then I recalled you told to use MKVmerge.exe on scenedetect folder, so I used portable and copy MKVmerge.exe and it works flawlessly.
by the way, how to use ffmpeg with scenedetect. kindly reply me step by step for being total noob on programing field. thanks.

**Comment by Breakthrough** [comment]
Hi @raj6996;

You can get both ffmpeg/mkvmerge from here:
https://github.com/Breakthrough/PySceneDetect/blob/resources/third-party/split-video-progams-win64.7z?raw=true

Likewise, you do the same thing (just drop ffmpeg.exe where scenedetect.exe is).  I'll try to make the download link a little bit more apparent, and when I finalize the Windows release (portable/installer), it should include both programs for you as well.

Let me know if this solves it, thanks again for your help in testing the software!!

**Comment by raj6996** [comment]
I recently used 64bit python. so don't know why this I got error!
C:\Python37\Lib\site-packages\scenedetect>pip install scenedetect
Requirement already satisfied: scenedetect in c:\python37\lib\site-packages (0.5)
Requirement already satisfied: Click in c:\python37\lib\site-packages (from scenedetect) (6.7)
Requirement already satisfied: numpy in c:\python37\lib\site-packages (from scenedetect) (1.15.1)

Here is error:
C:\Python37\Lib\site-packages\scenedetect>scenedetect -i "G:\MGPM\MM2018.mp4" -o "G:\MGPM\A" detect-content list-scenes split-video --copy
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\scenedetect.exe\__main__.py", line 5, in <module>
  File "c:\python37\lib\site-packages\scenedetect\__init__.py", line 52, in <module>
    from scenedetect.scene_manager import SceneManager
  File "c:\python37\lib\site-packages\scenedetect\scene_manager.py", line 55, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

C:\Python37\Lib\site-packages\scenedetect>

**Comment by Breakthrough** [comment]
@raj6996;

You need to `pip install opencv-python` as above again.

**Comment by raj6996** [comment]
Thanks Breakthrough, awesome and fast support!

**Comment by raj6996** [comment]
Mkvmerge works great, but output files are .mkv instead of mp4.
As Vegas software is not works on mkv. so I need to re-encode to mp4 from mkv, 
I replace ffmpeg.exe with mkvmerge on scenedetect, but it give me this.
> 
> Error: Invalid value for split-video: mkvmerge is required for split-video -c/--copy.
> Install the above tool to enable video splitting support.
Is there anyway to copy option with ffmpeg.

**Comment by Breakthrough** [comment]
Fixed in 6c4c8d491f7950a5ef91a0351c9d6acde0282500.

**Comment by Breakthrough** [comment]
Original fix caused regression which was captured by #111.

**Comment by mrobe** [comment]
I am getting this same error on macOS 10.13.6. Tried everything in this thread but no joy.

What to do?

**Comment by hlgope** [comment]
Thanks...
