### ISSUE TITLE
Randomize clip order options

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#74]
**Description of Problem & Solution**
Randomize clip order option, if possible like 1.3.5.7 and 2.4.6 or 1.2.9.4.3.8

**Media Examples:**

**Proposed Implementation:**
moviepy, ffmpeg has randomize option, so will you implement your project.

**Comment by wjs018** [comment]
I don't actually see where this is implemented in moviepy (though I am by no means a moviepy expert). If you want to randomize the order of clips in `PySceneDetect`, you can do so by shuffling the detected scene list.

```python
import scenedetect
import random

video_mgr = scenedetect.VideoManager([video_file])    #put your filename in this line
stats_mgr = scenedetect.stats_manager.StatsManager()
scene_mgr = scenedetect.SceneManager(stats_mgr)

# Using a ContentDetector
scene_mgr.add_detector(scenedetect.ContentDetector(threshold=30, min_scene_len=10))

# Detect the scenes
video_mgr.start()
scene_mgr.detect_scenes(frame_source=video_mgr)

# Get our scene list and randomize it
base_timecode = video_mgr.get_base_timecode()
scene_list = scene_mgr.get_scene_list(base_timecode)
random.shuffle(scene_list)    #scene_list is now randomized
```

**Comment by Breakthrough** [comment]
I agree with @wjs018 on this one, once you have the scene boundaries, randomization is up to the end user.  Closing this issue unless other people feel it may add value.
