### ISSUE TITLE
Support fast-copy mode with FFmpeg instead of only Mkvmerge

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#77]
**Bug/Issue Description:**
Mkvmerge works great, but output files are .mkv instead of mp4.
As Vegas software is not works on mkv. so I need to re-encode to mp4 from mkv, 
I replace ffmpeg.exe with mkvmerge on scenedetect, but it give me this.
> 
> Error: Invalid value for split-video: mkvmerge is required for split-video -c/--copy.
> Install the above tool to enable video splitting support.
Is there anyway to copy option with ffmpeg, I don't need to re-encode!

**Computing Environment:**
 - OS:  64bit Win10 Pro
 - Python Version: 64bit 3.7.0
 - OpenCV Version: Latest

**Comment by Breakthrough** [comment]
I'm just not sure the best way to resolve the discrepancy of when you have both tools installed, which one should be used.  I could allow specifying the file extension for the video name and using that, but that feels inelegant.

I think the best way to solve this is to have a settings file of some kind, and maybe have a command line option to set which program will be used (e.g. `scenedetect set copy_program ffmpeg`).

**Comment by anujtyagi2802** [comment]
scenedetect -i video.mp4 -s video.stats.csv detect-content list-scenes -n gives syntax error

**Comment by Breakthrough** [comment]
Hi @anujtyagi2802;

Would you be able to submit a new issue report for that, or is it related to #77?  Could you share the console output as well as the debug output to help investigate the error you're having?

Thank you!

**Comment by anujtyagi2802** [comment]
![Screenshot from 2019-09-12 11-31-16](https://user-images.githubusercontent.com/35371056/64757846-de964200-d550-11e9-844e-8e5dc3ae94c5.png)

**Comment by Breakthrough** [comment]
This is now possible by setting the `-a`/`--override-args` option with the `split-video` command, e.g.:

`split-video -a "-c:v copy -c:a flac"`

**Comment by Breakthrough** [comment]
Revisiting this for v1.0.  I'm still not sure if ffmpeg or mkvmerge should be the default, but think it should stay at mkvmerge for now, only falling back to `ffmpeg` if it's not available.

To address this more generally though, we can change `-c/--copy` to take an additional argument so you can force a particular tool, e.g.:

    # use mkvmerge if available, otherwise ffmpeg
    scenedetect [...] split-video --copy
    # use ffmpeg (can also specify "-c f" as a short option)
    scenedetect [...] split-video --copy ffmpeg
    # use mkvmerge (can also specify "-c m" as a short option)
    scenedetect [...] split-video --copy mkvmerge

**Comment by Breakthrough** [comment]
In v1.0, `-c`/`--copy` will now use ffmpeg, and added a separate option `-m`/`--mkvmerge` to use mkvmerge for splitting instead.

**Comment by Breakthrough** [comment]
This is now available in the v0.6 beta.
