### ISSUE TITLE
Error: no such option: -e

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#78]
**Bug/Issue Description:**
PS C:\Users\YL> scenedetect -i "G:\MGPM\MM\FFo.mp4" -s 00:30:35.370 -e 01:13:44.160 -o "G:\MGPM\1" detect-threshold -t 12 -p 95 list-scenes split-video --copy
Error: no such option: -e
**Or,**
PS C:\Users\YL> scenedetect -s 00:30:35.37 -e 01:13:44.16 -i "G:\MGPM\MM\FFo.mp4" -o G:\MGPM\1" detect-threshold -t 12 -p 95 list-scenes split-video --copy
Error: no such option: -e

**Computing Environment:**
 - OS: 64bit Win10
 - Python Version: x64 P3.7
 - OpenCV Version: Latest

**Comment by Breakthrough** [comment]
Hi @raj6996;

I think you are missing the `time` command.  The correct command should be:

    PS C:\Users\YL> scenedetect -i "G:\MGPM\MM\FFo.mp4" -o "G:\MGPM\1" time -s 00:30:35.370 -e 01:13:44.160 detect-threshold -t 12 -p 95 list-scenes split-video --copy

or


    PS C:\Users\YL> scenedetect -i "G:\MGPM\MM\FFo.mp4" -o G:\MGPM\1" time  -s 00:30:35.37 -e 01:13:44.16 detect-threshold -t 12 -p 95 list-scenes split-video --copy
Error: no such option: -e
