### ISSUE TITLE
Error: no such option: -d

### ISSUE THREAD

**Issue by dmiszkiewicz** [Breakthrough/PySceneDetect#80]
Command: scenedetect --input fails.mp4 detect-content list-scenes -o myvideo_scenes.csv -d 2
Error:
[PySceneDetect] Loaded 1 video, framerate: 29.97 FPS, resolution: 1280 x 720
[PySceneDetect] Downscale factor set to 5, effective resolution: 256 x 144
[PySceneDetect] No scene detectors specified (detect-content, detect-threshold, etc...),
  or failed to process all command line arguments.
Error: no such option: -d

Computing Environment 1:
 - OS: Ubuntu Server 16.04LTS
 - Python Version: Python 3.5.2
 - OpenCV Version: opencv-python (3.4.3.18)

Computing Environment 2:
 - OS: Mac OS 10.13.6
 - Python Version: Python 2.7.15
 - OpenCV Version: opencv-python 3.4.2.17

**Comment by Breakthrough** [comment]
Hi @dmiszkiewicz;

Are you trying to use the `downscale` option?  If so, it needs to be specified before any commands, for example:

    scenedetect --input fails.mp4 -d 2 detect-content list-scenes -o myvideo_scenes.csv 

Is this what you were intending to do?

**Comment by dmiszkiewicz** [comment]
Yes, thank you very much for your support! This project really interests me. I would like to make contributions in the near future(learning python now).
