### ISSUE TITLE
Object Detection feature Implementation 

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#82]
**Proposed Implementation:**
Sound weird, but is it possible to implement object detection into this project. it will be awesome project. I was thinking it one months ago, but clueless how to do it. As you are more active on this project so you may be add this feature in the future.

**Comment by Breakthrough** [comment]
Hi @raj6996;

Unfortunately the project has too many milestones right now and I want to keep the focus of PySceneDetect as narrow as possible until all existing milestones have been achieved.  At that point I will gladly reconsider such ideas as this.

I definitely will reconsider this in the future, but this is a large feature which requires significant research before implementing.  Sorry about that, I do hope you understand.

Thank you for your submission!
