### ISSUE TITLE
module 'scenedetect.detectors' has no attribute 'get_available'

### ISSUE THREAD

**Issue by ishandutta2007** [Breakthrough/PySceneDetect#84]
import scenedetect
    scene_detectors = scenedetect.detectors.get_available()
    smgr_content = scenedetect.manager.SceneManager(PySceneDetectArgs(input=video_path, type='content'), scene_detectors)

> module 'scenedetect.detectors' has no attribute 'get_available'

scenedetect version is 0.5 and python version is 3.5

**Comment by Breakthrough** [comment]
Hi @ishandutta2007 

I removed the get_available() method in v0.5 as it's not really needed to get all detection methods at runtime.  This could also be achieved in a smarter way I think, if required, going forwards, however I'm still open to the older style.

Thoughts?

**Comment by ishandutta2007** [comment]
Can you quickly help me understand how would the above code now look like in v0.5?

**Comment by wjs018** [comment]
@ishandutta2007 
You just add the detector directly. Here is a simplified example from one of my functions where I add a content detector. To see the whole thing, look at the `analyze_video` function [here](https://github.com/wjs018/QuantitativeEditing/blob/2992425c7c21a632ca08ee2d9ba7aea87d6edde2/QuantitativeEditing/vp9_issue_example.py#L10).

```python
import scenedetect

video_mgr = scenedetect.VideoManager([video_file])    #put your filename in this line
stats_mgr = scenedetect.stats_manager.StatsManager()
scene_mgr = scenedetect.SceneManager(stats_mgr)

# Now add the content  detector
scene_mgr.add_detector(scenedetect.ContentDetector(threshold=30, min_scene_len=10))
```

I haven't tried this, but you should be able to add multiple detectors with multiple calls to `add_detector`. Then, if any of your detectors triggers a scene break on a frame, it is included in the scene list. This would let you have both a `ContentDetector` and a `ThresholdDetector` (or your own custom detector) analyzing your video at the same time.

**Comment by ishandutta2007** [comment]
Well if you are seeking advices, I would say the newer approach is fine. 

In fact as end user I would prefer the APIs to be as high level as possible, as much abstracted out as possible. I may not even care to expose any of `StatsManager`, `VideoManager` or `SceneManager` classes. Something like

```
import scenedetect
video = scenedetect.load(video_file_name)
scene_list = video.get_scenes(threshold=30, min_scene_len=10)
scene_list[2].write(scene_file_name);
```

Anyways whatever you are doing doesn't seem to be too out of the standards, 
I am saying just from the point of view of a programmers ease of access.
Whatever you decide, just keep docs and ecamples updated, Cheers.
