### ISSUE TITLE
PySceneDetect causes exception in tqdm

### ISSUE THREAD

**Issue by workflowsguy** [Breakthrough/PySceneDetect#85]
**Bug/Issue Description:**
Every time at the end of executing `scenedetect`, the following error is displayed
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/usr/local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

```
**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using:

`scenedetect --input "somevideo.mp4" --output "outputpath" detect-content save-images`

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.
[BUG_REPORT.txt](https://github.com/Breakthrough/PySceneDetect/files/2569782/BUG_REPORT.txt)

**Expected Behavior:**
Execution should end without error

**Computing Environment:**
 - OS: [OSX]
 - Python Version: [3.7.1]
 - OpenCV Version: [3.4.3]

**Comment by Breakthrough** [comment]
I would have to say that this is a bug with tqdm, but I will double check... What version of tqdm are you using?

In the meantime I can consider an interm solution to suppress the exception, although I would like to understand what's causing this exactly before doing so.

Thanks for your report.

**Comment by workflowsguy** [comment]
@Breakthrough, there was a recent update of tdqm to version 4.31.1.
I did a quick test of PySceneDetect after upgrading, and the issue did not appear. Maybe this has solved it?

Thanks!

**Comment by Breakthrough** [comment]
Thanks for the feedback @workflowsguy.  Will close this unless it happens again, in which case feel free to re-open the issue.
