### ISSUE TITLE
Using pyscenedetect in lambda function?

### ISSUE THREAD

**Issue by jmsp** [Breakthrough/PySceneDetect#87]
Just came across `pyscenedetect` and it is awesome, I tested it out on my machine with a video and it worked great. I was wondering if it was possible to use this package in a lambda function by passing a video to it and then returning a csv or json with the scenes? Many thanks and great work!

**Comment by Breakthrough** [comment]
Hi @jmsp;

See [the example code here in the manual (link)](https://pyscenedetect-manual.readthedocs.io/en/latest/api/scene_manager.html#scenemanager-example) for an example of using the Python API to detect scenes and `print` a list of them.

Thank you for your interest.

**Comment by Breakthrough** [comment]
Hi @jmsp;

Due to inactivity on this issue, I will close it assuming it to be resolved.  If this is not the case, please feel free to re-open it or create a new issue.

Thank you!
