### ISSUE TITLE
Calling Save Images from Python Interface

### ISSUE THREAD

**Issue by KevinJ90825** [Breakthrough/PySceneDetect#88]
Description of Problem & Solution
I would like to be able to generate images for split scenes with the Python API, in the same way you can generate them with the CLI save-images command

Proposed Implementation:
The addition of an API method in the video-splitting module, ideally, or wherever else might be deemed appropriate.

**Comment by Breakthrough** [comment]
TODO: Add SaveImages command to the Python API.

**Comment by Breakthrough** [comment]
Implemented global function `scenedetect.scene_manager.generate_images`, and still TODO is to add an actual `save_images` method to the `SceneManager` which will invoke the `generate_images` function.

**Comment by Breakthrough** [comment]
This function will need to be modified either as part of #123 or another changeset afterwards.

**Comment by Breakthrough** [comment]
After #129 is merged, work on this will resume, which also needs to write unit tests for the new global function.

**Comment by Breakthrough** [comment]
This is now available in the v0.5.5 branch.  Still TODO is complete documentation and add unit tests.  It can be called via `scenedetect.scene_manager.generate_images` now.  Targeting v0.5.5 release now.

**Comment by Breakthrough** [comment]
This has been included in the v0.5.5 release.  Documentation for the `save_images()` function can be found [here (link)](https://pyscenedetect.readthedocs.io/projects/Manual/en/latest/api/scene_manager.html#scenedetect.scene_manager.save_images).
