### ISSUE TITLE
PySceneDetect working slow on Centos7

### ISSUE THREAD

**Issue by MichalKustra** [Breakthrough/PySceneDetect#91]
I am testing PySceneDetect on Centos7. 

Procesor: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
Ram: 2GB, SSD disk

I am using short test video. On two of my local machines (one has Windows, one has Linux and they are not so powerfull. Intel core I5, 8GB ram, SSD disks) it takes less than 5 seconds to process video. On Centos, for some reason it takes 45 seconds. 

Do you know why can it happen? Maybe there's configuration problem?

I am attaching link to video I am using for testing: http://stage.designrr.io/assets/video/night_sample_video.mp4

**Comment by MichalKustra** [comment]
SOLVED

After installing newest available versions of Python (3.6) and Opencv (4.0), PySceneDetect started to work way faster (It takes 1-2 seconds now for video which required 45 seconds before)

**Comment by Breakthrough** [comment]
Wow, interesting - I've measured speedups between Python 2.7/OpenCV 2.x and Python 3.x/OpenCV 3.x, but nothing of this magnitude (mine were on the order of 20-30% faster)...
