### ISSUE TITLE
delta_hsv_avg not in stats CSV

### ISSUE THREAD

**Issue by wearekolossum** [Breakthrough/PySceneDetect#95]
Hey there, i am trying to generate a stats file based on the goldeneye.mp4 from your examples. My command is:

scenedetect --input goldeneye.mp4 -s goldeneye.stats.csv detect-content

The stats file is generated (i appended it), but it is missing the delta_hsv_avg entry mentioned at https://pyscenedetect-manual.readthedocs.io/en/latest/cli/detectors.html#detect-content . 

Am i missing something in my command?

Thank you for your help and keep up the good work
Florian
[goldeneye.stats.csv.zip](https://github.com/Breakthrough/PySceneDetect/files/2954397/goldeneye.stats.csv.zip)

**Comment by Breakthrough** [comment]
Hi @wearesuperideal;

The column is actually called `content_val` (the average of the last 3 columns).  Sorry about that, there's definitely a mis-match between the code and the documentation.  I'll have to update the documentation in the next release.

Thanks!

**Comment by wearesuperideal** [comment]
Hey @Breakthrough , thanks for the info, that's what i thought. Just one question: how do you then get to a value of 27? I tried adding all values in "content_val" to one sum and then divert it with the number of the frames, but that gives me something like 7 or so. I got a number of 27 however when i did the same for all 4 columns and then add all the results to one sum, which gives something like 27.5 . Thanks for an info.

**Comment by Breakthrough** [comment]
@wearesuperideal could you provide me an example of the file generated by PySceneDetect in this case?  Just a few rows from the CSV would be sufficient.

I just checked the source code, and it definitely is calculating that column as the average of the other three:
https://github.com/Breakthrough/PySceneDetect/blob/master/scenedetect/detectors/content_detector.py#L104

Thanks.

**Comment by pertvirt** [comment]
> Hey @Breakthrough , thanks for the info, that's what i thought. Just one question: how do you then get to a value of 27? I tried adding all values in "content_val" to one sum and then divert it with the number of the frames, but that gives me something like 7 or so. I got a number of 27 however when i did the same for all 4 columns and then add all the results to one sum, which gives something like 27.5 . Thanks for an info.

I have the same question with you. I have tried some methods to determine threshold but I still don't get a number of 27.

**Comment by wearesuperideal** [comment]
Hey @Breakthrough , the CSV file can be found here: https://github.com/Breakthrough/PySceneDetect/files/2954397/goldeneye.stats.csv.zip . 

I can confirm that content_val is the average of the other three columns per row. However i can't get to a value of 27 for the goldeneye.mp4 as in your tutorial with "just" using the content_val column. Thanks for any help.

**Comment by Breakthrough** [comment]
Hi @wearesuperideal;

Sorry I just realized now, I think I misunderstood your initial question.  By 27 I assume you're talking about the "ideal" content threshold value for the Goldeneye clip from the example.

That value was selected by graphing the output stats-file to determine the correct threshold, but that was done manually by determining what threshold yielded the most correct results.  There's no automatic threshold detection in place yet, but this is something being planned for a future version.

It will likely have to be a heuristic-based method, or combine some kind of statistical methods to automatically determine the correct threshold based on mean/standard deviation.  In another issue in the tracker someone has shared an IPython Notebook with some statistics-based threshold determination, but also note that this requires two passes on a video (thus would require a statsfile to be efficient).

**Comment by wearesuperideal** [comment]
Hi @Breakthrough , alright, thanks for the info.

**Comment by Breakthrough** [comment]
Resolved in v0.5.4.
