### ISSUE TITLE
VEGAS VideoEditor implementation

### ISSUE THREAD

**Issue by haroldlinke** [Breakthrough/PySceneDetect#97]
Hi Brandon,
first of all thank you for you rgreat work pn PySceneDetect. It is a great tool.
I am working on an implementation Scenedetection solution for the VEGAS Pro video editor [https://www.vegascreativesoftware.com/gb/vegas-pro/](url).
The user can select one or several clips in the mediapool or one or several clips on the timeline and the clips are cut into pieces based on scene changes. I am using your PySceneDetect API to analys the clips.
As the user interface is a bit different froma command line I have added some features:

1. Configuration parameters are provided via a JSON file
2. In a preview window every 50th frame is shown including a progressbar (tqdm does not work in the environment)

During the adaptation I saw some oints where I think some performance improvements couldbe possible:

1. in the content detection you first convert colorspace to HSV, the you split and the you calculate the meab value over all panes using numpy.
I reduced tested the following approach, that workswell:
convert colorspace to HSV, then use the ABSDIFF function to determine the delat image, then the MEAN function to determin the mean value per color and then sum the results up as you did it.
Is there any cause why you do not use these openCV functions?
2. test showed that in many case using RGB instead of HSV provides good results too.  I therefore added a configuration parameter to select if HSV or RGB should be used
3. I do not see the need to save the last_frame in self.last_frame. self.last_hsv is sufficient. When self.last_hsv is None (e.g. at the start of the clip) it is sufficient to set delta_avg = 0 and skip the delta_avg calculation.

What do you think about these ideas? Are they valid or did I miss something?

I can provide you with the source code if you are interested.
The complete source code will be made available via Github.

Harold

**Comment by Breakthrough** [comment]
Hi @haroldlinke;

Thanks for sharing this!  Indeed the ideas you shared are valid, and are worth looking into.  I would definitely be interested in the modified source code if you're willing to share it.

Also feel free to submit any pull requests or issues for specific items you've mentioned above.

Thank you!!

**Comment by haroldlinke** [comment]
Hi Brandon,

 

I tried to create a Pull Request. As a direct upload was not possible I created a fork of your repository and then a pull request with this fork. As I am new to GitHub I may have done something wrong.

 

So I hope you received it and it is helpful.

 

Kind regards

Harold

 

Von: Brandon Castellano <notifications@github.com> 
Gesendet: Freitag, 5. April 2019 20:51
An: Breakthrough/PySceneDetect <PySceneDetect@noreply.github.com>
Cc: haroldlinke <harold.linke@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Breakthrough/PySceneDetect] VEGAS VideoEditor implementation (#97)

 

Hi @haroldlinke <https://github.com/haroldlinke> ;

Thanks for sharing this! Indeed the ideas you shared are valid, and are worth looking into. I would definitely be interested in the modified source code if you're willing to share it.

Also feel free to submit any pull requests or issues for specific items you've mentioned above.

Thank you!!

**Comment by Breakthrough** [comment]
Hi @haroldlinke;

Thank you so much for sharing the repo with me, I'll try to take a look when I have some time and see how is best to move forwards.  In the meantime, feel free to keep me posted with your progress in releasing the plugin, thanks!
